#' Create folder structure for personal species photos
#'
#' @author
#' Martin Boucknooghe & Domingos Cardoso
#'
#' @description
#' This function creates an organized folder structure for storing personal photos
#' of species. It reads a species dataframe generated by \code{arboretum_data()}
#' and creates one photo folder per species inside an \code{arboretum_photos/}
#' directory.
#'
#' The function is designed to be used after \code{arboretum_data()} and before
#' generating final labels or minisites with functions such as \code{arboretum_labels()}.
#' When personal photos are placed in the appropriate species folders, downstream
#' functions can use them instead of relying only on built-in or automatically
#' retrieved image resources.
#'
#' @param data_path Required. Character string giving the path to the input data file
#'   generated by \code{arboretum_data()}. The file must be in CSV or Excel
#'   format and should contain, at minimum, the columns \code{taxonName} and
#'   \code{family}. Passing \code{NULL} will result in an error when the input data
#'   are read.
#' @param verbose Logical. If \code{TRUE}, progress messages are printed to the
#'   console. Default is \code{TRUE}.
#'
#' @return
#' Invisibly returns \code{NULL}. The function is called for its side effects:
#' \itemize{
#'   \item creates the main \code{arboretum_photos/} directory, if it does not already
#'     exist;
#'   \item creates one species-specific subfolder per taxon;
#'   \item preserves existing folders and creates only missing folders.
#' }
#'
#' @details
#' The function follows three main steps:
#'
#' \enumerate{
#'   \item \strong{Input data loading}
#'   \itemize{
#'     \item Reads the input species data using an internal helper function.
#'     \item Supports CSV and Excel files.
#'     \item Expects species names in \code{taxonName} and family names in
#'       \code{family}.
#'   }
#'
#'   \item \strong{Folder creation}
#'   \itemize{
#'     \item Creates a main folder named \code{arboretum_photos}.
#'     \item Creates one subfolder for each species in the input data.
#'     \item Subfolder names are built from family, species name, and the suffix
#'       \code{photos}.
#'     \item Species names are converted to folder-safe names by replacing spaces with
#'       underscores.
#'   }
#'
#'   \item \strong{Photo placement}
#'   \itemize{
#'     \item Users should place their photo files in the corresponding species folder.
#'     \item Common image formats such as JPG, JPEG, PNG, and similar formats can be
#'       used, depending on the downstream functions that read the photos.
#'     \item The photo folders are intended to be used by downstream label or minisite
#'       generation functions.
#'   }
#' }
#'
#' The folder naming pattern is:
#'
#' \preformatted{
#' FAMILY_Genus_species_photos
#' }
#'
#' For example:
#'
#' \preformatted{
#' arboretum_photos/
#' ├── ARECACEAE_Euterpe_edulis_photos/
#' ├── FABACEAE_Paubrasilia_echinata_photos/
#' └── ...
#' }
#'
#' @note
#' \itemize{
#'   \item This function does not download, validate, resize, rename, or convert image
#'     files. It only prepares the folder structure for manual photo placement.
#'   \item Existing folders are not deleted or overwritten.
#'   \item If \code{arboretum_photos/} already exists, the function checks each species
#'     folder and creates only those that are missing.
#'   \item The function should generally be run after \code{arboretum_data()} and
#'     before \code{arboretum_labels()}.
#' }
#'
#' @seealso
#' \code{\link{arboretum_data}},
#' \code{\link{arboretum_labels}}
#'
#' @examples
#' \dontrun{
#' # Create photo folders from a CSV file generated by arboretum_data()
#' arboretum_photos(
#'   data_path = "arboretum_data/arboretum_data.csv"
#' )
#'
#' # Create photo folders from an Excel file
#' arboretum_photos(
#'   data_path = "arboretum_data/arboretum_data.xlsx",
#'   verbose = TRUE
#' )
#'
#' # Suppress progress messages
#' arboretum_photos(
#'   data_path = "arboretum_data/arboretum_data.csv",
#'   verbose = FALSE
#' )
#' }
#'
#' @importFrom utils read.csv
#' @importFrom openxlsx read.xlsx
#' @importFrom tools file_ext
#'
#' @export


arboretum_photos <- function(data_path = NULL,
                             verbose = TRUE) {

  # Read input data
  df <- .read_species_data(data_path, verbose)

  # Create base directory
  base_dir <- "arboretum_photos"

  if (!dir.exists(base_dir)) {
    dir.create(base_dir, recursive = TRUE)
    if (verbose) {
      message("Created base directory: ", base_dir)
    }
  } else {
    if (verbose) {
      message("Base directory already exists: ", base_dir)
      message("Creating only missing species folders...")
    }
  }

  # Prepare species names and families
  spp <- gsub("\\s", "_", df$taxonName)
  fam <- toupper(df$family)

  # Create folders for each species
  for (i in seq_along(spp)) {
    folder_path <- file.path(base_dir, paste(fam[i], spp[i], "photos", sep = "_"))

    if (!dir.exists(folder_path)) {
      dir.create(folder_path, recursive = TRUE)
      if (verbose) {
        message("Created folder: ", paste(fam[i], spp[i], sep = "_"))
      }
    } else if (verbose) {
      message("Folder already exists (skipping): ", folder_path)
    }
  }

  if (verbose) {
    message("\nEmpty folders for adding personal photos successfully created!\n")
    message("Place your photo files (JPG, PNG, etc.) in the respective species folders.")
    message("The HTML labels will automatically use these photos when present.")
  }

  invisible(NULL)
}
