#' Create folder structure and phrase files for personal audio recordings
#'
#' @author
#' Martin Boucknooghe & Domingos Cardoso
#'
#' @description
#' This function creates an organized folder structure for storing personal audio
#' recordings of species descriptions and generates an HTML guide with the phrases
#' to be recorded. It is designed to be used **after** running `arboretum_data()`
#' and **before** running `arboretum_labels()` when users want to provide their
#' own audio files instead of relying only on browser text-to-speech.
#'
#' In addition to the built-in translated languages (`"pt"`, `"en"`, `"fr"`,
#' and `"es"`), the function can optionally prepare folders for one additional
#' language through `add_lang`. This is useful when a project needs to include
#' community-based or locally relevant audio, such as recordings in an Indigenous
#' language, even if that language is not yet fully incorporated into the package
#' interface or translation system.
#'
#' The `add_lang` argument is intended as a flexible, intermediate solution:
#' it allows users to organize and add personal audio for an extra language while
#' the rest of the website remains in the package-supported interface languages.
#'
#' @param data_path Character string. Path to the input data file (CSV or Excel format)
#'   generated by `arboretum_data()`.
#' @param printed_lang Character vector. Built-in language(s) to generate folders and
#'   phrases for. Accepted values are `"pt"`, `"en"`, `"fr"`, and `"es"`.
#' @param add_lang Character string or `NULL`. Optional code for one additional
#'   language to include in the folder structure for personal recordings, for
#'   example `"PANARA"` or `"TUKANO"`. This argument is intended for cases where
#'   users want to add custom community or local-language audio without translating
#'   the full package interface. When supplied, one extra recording folder per
#'   species is created using that language code.
#' @param verbose Logical. If `TRUE`, prints progress messages to the console.
#'
#' @return Invisibly returns `NULL`.
#'
#' @details
#' The function creates an `arboretum_audios/` directory containing one folder per
#' species-language combination. Folder names follow the pattern:
#'
#' \preformatted{
#' FAMILY_Genus_species_LANG
#' }
#'
#' where `LANG` is one of `PT`, `EN`, `FR`, `ES`, or the custom value supplied in
#' `add_lang`.
#'
#' It also creates an HTML file named:
#'
#' \preformatted{
#' arboretum_audios/__personal_audio_recording_guide.html
#' }
#'
#' This guide helps users navigate across species and languages when preparing
#' personal recordings.
#'
#' @note
#' `add_lang` does not create a full translation workflow for the package interface.
#' It only prepares an additional language slot for custom audio recording, and is
#' especially useful in collaborative projects where accessibility in a community
#' language is needed before a complete website translation is available.
#'
#' @importFrom utils read.csv
#' @importFrom openxlsx read.xlsx
#' @importFrom tools file_ext
#' @importFrom jsonlite toJSON
#' @export

arboretum_audios <- function(data_path = NULL,
                             printed_lang = c("pt", "en", "fr", "es"),
                             add_lang = NULL,
                             verbose = TRUE) {

  printed_lang <- .arg_check_printed_lang(printed_lang)

  df <- .read_species_data(data_path, verbose)

  audio_dir <- "arboretum_audios"
  lang_codes <- c("EN", "ES", "FR", "PT")

  if (!is.null(add_lang) && nzchar(add_lang)) {
    lang_codes <- unique(c(lang_codes, toupper(add_lang)))
  }

  spp <- gsub("\\s", "_", df$taxonName)
  fam <- toupper(df$family)

  if (!dir.exists(audio_dir)) {
    if (verbose) {
      message("Empty folders for adding personal audios successfully created!\n")
    }
    dir.create(audio_dir, recursive = TRUE)
    for (i in seq_along(spp)) {
      for (lang in lang_codes) {
        folder_path <- file.path(audio_dir, paste(fam[i], spp[i], lang, sep = "_"))
        dir.create(folder_path, recursive = TRUE)
      }
    }
  }

  audio_ui_strings <- list(
    en = list(
      html_lang = "en",
      title = "Personal Audio Recording Guide",
      subtitle = "Use this file to record your own species audios before generating the HTML labels and minisite.",
      search_placeholder = "Search species or family name...",
      index_title = "Index",
      no_results = "No species matched your search.",
      back_to_top = "Back to top",
      footer_note = "Use your browser search or the search field above to jump quickly across species.",
      family = "Family",
      generated_with = "Generated with"
    ),
    pt = list(
      html_lang = "pt",
      title = "Guia para Gravação de Áudios Pessoais",
      subtitle = "Use este arquivo para gravar seus próprios áudios das espécies antes de gerar os rótulos em HTML e o minisite.",
      search_placeholder = "Pesquisar nome da espécie ou família...",
      index_title = "Índice",
      no_results = "Nenhuma espécie corresponde à sua busca.",
      back_to_top = "Voltar ao topo",
      footer_note = "Use a busca do navegador ou o campo acima para navegar rapidamente entre as espécies.",
      family = "Família",
      generated_with = "Gerado com"
    ),
    fr = list(
      html_lang = "fr",
      title = "Guide d’Enregistrement Audio Personnel",
      subtitle = "Utilisez ce fichier pour enregistrer vos propres audios d’espèces avant de générer les étiquettes HTML et le minisite.",
      search_placeholder = "Rechercher le nom de l’espèce ou de la famille...",
      index_title = "Index",
      no_results = "Aucune espèce ne correspond à votre recherche.",
      back_to_top = "Retour en haut",
      footer_note = "Utilisez la recherche du navigateur ou le champ ci-dessus pour naviguer rapidement entre les espèces.",
      family = "Famille",
      generated_with = "Généré avec"
    ),
    es = list(
      html_lang = "es",
      title = "Guía para Grabar Audios Personales",
      subtitle = "Use este archivo para grabar sus propios audios de especies antes de generar las etiquetas HTML y el minisitio.",
      search_placeholder = "Buscar nombre de la especie o familia...",
      index_title = "Índice",
      no_results = "Ninguna especie coincide con su búsqueda.",
      back_to_top = "Volver arriba",
      footer_note = "Use la búsqueda del navegador o el campo superior para navegar rápidamente entre las especies.",
      family = "Familia",
      generated_with = "Generado con"
    )
  )

  lang_button_label <- c(
    en = "English",
    pt = "Português",
    fr = "Français",
    es = "Español"
  )

  missing_langs <- setdiff(printed_lang, names(lang_button_label))
  if (length(missing_langs) > 0) {
    lang_button_label[missing_langs] <- toupper(missing_langs)
  }

  # Generate phrases for each requested language
  phrases_out <- .build_arboretum_phrases(
    data_path = NULL,
    df = df,
    printed_lang = printed_lang,
    add_lang = add_lang,
    verbose = verbose
  )

  printed_lang <- phrases_out$printed_lang
  html_phrases <- phrases_out$html_phrases

  output_path <- file.path(audio_dir, "__personal_audio_recording_guide.html")
  .save_phrase_html(
    df = df,
    audio_ui_strings = audio_ui_strings,
    lang_button_label = lang_button_label,
    printed_lang = printed_lang,
    html_phrases = html_phrases,
    output_path = output_path,
    verbose = verbose
  )

  invisible(NULL)
}

.save_phrase_html <- function(df,
                              audio_ui_strings,
                              lang_button_label,
                              printed_lang,
                              html_phrases,
                              output_path,
                              verbose) {
  initial_lang <- printed_lang[1L]
  ui_strings_json <- jsonlite::toJSON(audio_ui_strings[printed_lang], auto_unbox = TRUE)
  lang_buttons_html <- .build_language_buttons(printed_lang, initial_lang, lang_button_label)
  index_html <- .build_species_index(df)
  cards_html <- .build_species_cards(df, printed_lang, html_phrases, initial_lang)

  html <- paste0(
    '<!DOCTYPE html>
<html lang="', .escape_html(audio_ui_strings[[initial_lang]]$html_lang), '">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>', .escape_html(audio_ui_strings[[initial_lang]]$title), '</title>
<style>
:root {
  --bg: #f6f3ee;
  --panel: #fffdf9;
  --ink: #1f2937;
  --muted: #6b7280;
  --line: #e5ded3;
  --accent: #2f6f57;
  --accent-soft: #e7f2ec;
  --shadow: 0 10px 30px rgba(0, 0, 0, 0.08);
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  color: var(--ink);
  background: var(--bg);
  line-height: 1.6;
}
.container {
  max-width: 1100px;
  margin: 0 auto;
  padding: 32px 20px 60px;
}
.hero {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 18px;
  padding: 24px;
  box-shadow: var(--shadow);
  margin-bottom: 24px;
}
.hero-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
}
.hero h1 {
  margin: 0 0 8px;
  font-size: 2rem;
}
.hero p {
  margin: 0;
  color: var(--muted);
}
.lang-switch {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
.lang-btn {
  padding: 8px 12px;
  border: 1px solid #d4e4d4;
  border-radius: 10px;
  background: #f0f7f0;
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--accent);
}
.lang-btn.active {
  background: var(--accent);
  color: #fff;
  border-color: var(--accent);
}
.search-wrap {
  position: sticky;
  top: 0;
  z-index: 10;
  background: linear-gradient(to bottom, var(--bg) 80%, rgba(246,243,238,0));
  padding: 16px 0 18px;
}
.search-box {
  width: 100%;
  padding: 14px 16px;
  border-radius: 14px;
  border: 1px solid var(--line);
  font-size: 1rem;
  background: #fff;
}
.index-panel {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 18px;
  padding: 20px;
  box-shadow: var(--shadow);
  margin-bottom: 24px;
}
.index-panel h2 {
  margin-top: 0;
}
.index-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 10px;
}
.index-link {
  display: block;
  text-decoration: none;
  color: var(--accent);
  background: var(--accent-soft);
  border-radius: 12px;
  padding: 10px 12px;
  border: 1px solid #d4e7dc;
}
.cards {
  display: grid;
  gap: 18px;
}
.species-card {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 18px;
  padding: 22px;
  box-shadow: var(--shadow);
}
.species-header h2 {
  margin: 0 0 4px;
  font-size: 1.5rem;
}
.family {
  margin: 0 0 14px;
  color: var(--muted);
  font-weight: 700;
  letter-spacing: 0.03em;
}
.lang-block + .lang-block {
  margin-top: 14px;
  padding-top: 14px;
  border-top: 1px solid var(--line);
}
.lang-block h3 {
  margin: 0 0 6px;
  font-size: 1rem;
  color: var(--accent);
}
.lang-block p {
  margin: 0;
}
.back-top {
  display: inline-block;
  margin-top: 16px;
  color: var(--muted);
  text-decoration: none;
  font-size: 0.95rem;
}
.empty-state {
  display: none;
  margin-top: 12px;
  color: var(--muted);
}
.footer-note {
  margin-top: 22px;
  color: var(--muted);
  font-size: 0.95rem;
}
.hidden {
  display: none !important;
}
.subtitle-link {
  color: inherit;
  font-weight: 700;
  text-decoration: none;
}
.subtitle-link:hover {
  text-decoration: underline;
}
.record-root-wrap {
  margin-top: 14px;
  display: flex;
  gap: 10px;
  align-items: center;
  flex-wrap: wrap;
}
.record-root-status {
  color: var(--muted);
  font-size: 0.95rem;
}
.record-controls {
  display: flex;
  gap: 8px;
  align-items: center;
  flex-wrap: wrap;
  margin-top: 10px;
}
.record-btn,
.stop-record-btn {
  padding: 7px 11px;
  border: 1px solid #d4e4d4;
  border-radius: 10px;
  background: #f0f7f0;
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--accent);
}
.stop-record-btn {
  background: #faf3f0;
}
.record-status {
  color: var(--muted);
  font-size: 0.9rem;
  min-width: 80px;
}
</style>
</head>
<body>
<div class="container" id="top">
  <section class="hero">
    <div class="hero-top">
      <div class="hero-copy">
        <h1 id="pageTitle" data-i18n="title">', .escape_html(audio_ui_strings[[initial_lang]]$title), '</h1>
        <p id="pageSubtitle">', .audio_subtitle_html(audio_ui_strings, initial_lang), '</p>
      </div>
      <div class="lang-switch">', lang_buttons_html, '</div>
    </div>
    <div class="record-root-wrap">
      <button id="pickAudioRoot" class="lang-btn" type="button">📁 Choose audio folder</button>
      <span id="audioRootStatus" class="record-root-status"></span>
    </div>
  </section>

  <div class="search-wrap">
    <input id="searchInput" class="search-box" type="text" placeholder="', .escape_html(audio_ui_strings[[initial_lang]]$search_placeholder), '">
  </div>

  <section class="index-panel">
    <h2 id="indexTitle" data-i18n="index_title">', .escape_html(audio_ui_strings[[initial_lang]]$index_title), '</h2>
    <div id="indexGrid" class="index-grid">
      ', index_html, '
    </div>
    <p id="emptyState" class="empty-state" data-i18n="no_results">', .escape_html(audio_ui_strings[[initial_lang]]$no_results), '</p>
  </section>

  <section id="cards" class="cards">
    ', cards_html, '
  </section>

  <p id="footerNote" class="footer-note" data-i18n="footer_note">', .escape_html(audio_ui_strings[[initial_lang]]$footer_note), '</p>
</div>

<script>
(function () {
  const uiStrings = ', ui_strings_json, ';
  const generatedDate = "', .escape_html(as.character(Sys.Date())), '";
  let currentLang = "', initial_lang, '";
  let audioRootHandle = null;
  let mediaRecorder = null;
  let mediaStream = null;
  let recordedChunks = [];
  let currentSection = null;

  const input = document.getElementById("searchInput");
  const cards = Array.from(document.querySelectorAll(".species-card"));
  const links = Array.from(document.querySelectorAll(".index-link"));
  const emptyState = document.getElementById("emptyState");
  const langButtons = Array.from(document.querySelectorAll(".lang-btn"));
  const audioRootStatus = document.getElementById("audioRootStatus");

  function escapeHtml(text) {
    return String(text)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function setStatus(section, value) {
    const node = section ? section.querySelector(".record-status") : null;
    if (node) node.textContent = value || "";
  }

  function applyLanguage(lang) {
    const ui = uiStrings[lang] || uiStrings.en;
    currentLang = lang;

    document.documentElement.lang = ui.html_lang || lang;
    document.title = ui.title;
    document.getElementById("pageTitle").textContent = ui.title;
    document.getElementById("pageSubtitle").innerHTML =
      escapeHtml(ui.subtitle) + "<br>" +
      escapeHtml(ui.generated_with) + " <a href=\\"https://github.com/DBOSlab/aRboretum\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"subtitle-link\\">aRboretum</a> " +
      generatedDate + ".";
    document.getElementById("indexTitle").textContent = ui.index_title;
    document.getElementById("footerNote").textContent = ui.footer_note;
    document.getElementById("searchInput").placeholder = ui.search_placeholder;
    document.getElementById("emptyState").textContent = ui.no_results;

    document.querySelectorAll("[data-i18n=\\"family\\"]").forEach(el => {
      el.textContent = ui.family;
    });

    document.querySelectorAll("[data-i18n=\\"back_to_top\\"]").forEach(el => {
      el.textContent = ui.back_to_top;
    });

    document.querySelectorAll(".lang-content").forEach(el => {
      el.classList.toggle("hidden", el.dataset.lang !== lang);
    });

    langButtons.forEach(btn => {
      btn.classList.toggle("active", btn.dataset.lang === lang);
    });
  }

  function applyFilter() {
    const q = input.value.trim().toLowerCase();
    let visibleCount = 0;

    cards.forEach(card => {
      const speciesName = (card.dataset.name || "").toLowerCase();
      const familyText = (card.querySelector(".family")?.textContent || "").toLowerCase();
      const visibleLangText = Array.from(card.querySelectorAll(".lang-content"))
        .filter(el => !el.classList.contains("hidden"))
        .map(el => el.textContent || "")
        .join(" ")
        .toLowerCase();

      const searchableText = [speciesName, familyText, visibleLangText].join(" ");
      const match = searchableText.includes(q);

      card.classList.toggle("hidden", !match);
      if (match) visibleCount += 1;
    });

    links.forEach(link => {
      const match = (link.dataset.name || "").toLowerCase().includes(q);
      link.classList.toggle("hidden", !match);
    });

    emptyState.style.display = visibleCount === 0 ? "block" : "none";
  }

  async function pickAudioRoot() {
    if (!window.showDirectoryPicker) {
      alert("Direct folder saving is supported in Chromium-based browsers when this page is served from localhost or HTTPS.");
      return;
    }

    try {
      audioRootHandle = await window.showDirectoryPicker();
      if (audioRootStatus) {
        audioRootStatus.textContent = "Folder selected: " + audioRootHandle.name;
      }
    } catch (err) {
      console.error(err);
    }
  }

  async function getOrCreateSubfolder(rootHandle, folderName) {
    return await rootHandle.getDirectoryHandle(folderName, { create: true });
  }

  async function saveRecordingToFolder(blob, sectionEl) {
    if (!audioRootHandle) {
      throw new Error("Please choose the audio root folder first.");
    }

    const family = sectionEl.dataset.family;
    const folderSpecies = sectionEl.dataset.folderSpecies;
    const langSuffix = sectionEl.dataset.langSuffix;
    const subfolderName = `${family}_${folderSpecies}_${langSuffix}`;
    const filename = `${family}_${folderSpecies}_${langSuffix}.webm`;

    const subfolder = await getOrCreateSubfolder(audioRootHandle, subfolderName);
    const fileHandle = await subfolder.getFileHandle(filename, { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(blob);
    await writable.close();
  }

  async function startRecording(sectionEl) {
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      alert("Audio recording is not supported in this browser.");
      return;
    }

    if (!audioRootHandle) {
      alert("Please choose the audio root folder first.");
      return;
    }

    if (mediaRecorder && mediaRecorder.state !== "inactive") {
      alert("A recording is already in progress.");
      return;
    }

    currentSection = sectionEl;
    recordedChunks = [];
    setStatus(sectionEl, "Recording...");

    try {
      mediaStream = await navigator.mediaDevices.getUserMedia({ audio: true });
      mediaRecorder = new MediaRecorder(mediaStream);

      mediaRecorder.ondataavailable = function(event) {
        if (event.data && event.data.size > 0) {
          recordedChunks.push(event.data);
        }
      };

      mediaRecorder.onstop = async function() {
        try {
          const blob = new Blob(recordedChunks, { type: mediaRecorder.mimeType || "audio/webm" });
          await saveRecordingToFolder(blob, currentSection);
          setStatus(currentSection, "Saved");
        } catch (err) {
          console.error(err);
          setStatus(currentSection, "Save failed");
        } finally {
          if (mediaStream) {
            mediaStream.getTracks().forEach(track => track.stop());
          }
          mediaStream = null;
          mediaRecorder = null;
          recordedChunks = [];
          currentSection = null;
        }
      };

      mediaRecorder.start();
    } catch (err) {
      console.error(err);
      setStatus(sectionEl, "Mic denied");
      if (mediaStream) {
        mediaStream.getTracks().forEach(track => track.stop());
      }
      mediaStream = null;
      mediaRecorder = null;
      recordedChunks = [];
      currentSection = null;
    }
  }

  function stopRecording(sectionEl) {
    if (!mediaRecorder || mediaRecorder.state === "inactive") {
      setStatus(sectionEl, "Idle");
      return;
    }
    setStatus(sectionEl, "Saving...");
    mediaRecorder.stop();
  }

  input.addEventListener("input", applyFilter);

  langButtons.forEach(btn => {
    btn.addEventListener("click", function () {
      if (this.id !== "pickAudioRoot") {
        applyLanguage(this.dataset.lang);
      }
    });
  });

  document.getElementById("pickAudioRoot")?.addEventListener("click", pickAudioRoot);

  document.querySelectorAll(".record-btn").forEach(btn => {
    btn.addEventListener("click", function () {
      const section = this.closest(".lang-block");
      if (section) startRecording(section);
    });
  });

  document.querySelectorAll(".stop-record-btn").forEach(btn => {
    btn.addEventListener("click", function () {
      const section = this.closest(".lang-block");
      stopRecording(section);
    });
  });

  applyLanguage(currentLang);
})();
</script>
</body>
</html>'
  )

  writeLines(html, con = output_path, useBytes = TRUE)

  if (verbose) {
    message("Phrases saved to: ", output_path)
  }
}


.build_species_cards <- function(df, printed_lang, html_phrases, initial_lang) {
  cards <- vector("character", length(df$taxonName))

  for (i in seq_along(df$taxonName)) {
    species_name <- .normalize_text(df$taxonName[i])
    family_name <- .normalize_text(df$family[i])
    species_id <- .slugify(species_name)
    folder_species <- .folder_species_name(species_name)
    family_upper <- toupper(family_name)

    lang_blocks <- character(0)

    for (lang in printed_lang) {
      base_text <- html_phrases[[lang]][[species_name]]
      base_text <- gsub("[<]i[>]|[<][/]i[>]", "", base_text)
      base_text <- .normalize_text(base_text, ensure_period = FALSE)

      extra_text <- .get_extra_phrase_text(df, i, lang)

      full_text <- base_text
      if (!is.null(extra_text)) {
        full_text <- paste(full_text, extra_text)
      }
      full_text <- .normalize_text(full_text, ensure_period = FALSE)

      hidden_class <- if (lang == initial_lang) "" else " hidden"
      lang_suffix <- .lang_suffix(lang)

      lang_blocks <- c(
        lang_blocks,
        paste0(
          '<section class="lang-block lang-content', hidden_class, '" ',
          'data-lang="', .escape_html(lang), '" ',
          'data-species="', .escape_html(species_name), '" ',
          'data-family="', .escape_html(family_upper), '" ',
          'data-folder-species="', .escape_html(folder_species), '" ',
          'data-lang-suffix="', .escape_html(lang_suffix), '">',
          '<h3>', .escape_html(.lang_label(lang)), '</h3>',
          '<p>', .escape_html(full_text), '</p>',
          '<div class="record-controls">',
          '<button type="button" class="record-btn">🎙 Record</button>',
          '<button type="button" class="stop-record-btn">⏹ Stop</button>',
          '<span class="record-status"></span>',
          '</div>',
          '</section>'
        )
      )
    }

    cards[i] <- paste0(
      '<article class="species-card" id="', species_id, '" data-name="', .escape_html(tolower(species_name)), '">',
      '<div class="species-header">',
      '<h2>', .escape_html(species_name), '</h2>',
      '<p class="family"><span data-i18n="family">Family</span>: ', .escape_html(family_name), '</p>',
      '</div>',
      paste(lang_blocks, collapse = "\n"),
      '<a class="back-top" href="#top" data-i18n="back_to_top">Back to top</a>',
      '</article>'
    )
  }

  paste(cards, collapse = "\n")
}

.lang_label <- function(lang) {
  switch(lang,
         pt = "Português",
         en = "English",
         fr = "Français",
         es = "Español",
         toupper(lang))
}

.lang_suffix <- function(lang) {
  switch(lang,
         pt = "PT",
         en = "EN",
         fr = "FR",
         es = "ES",
         toupper(lang))
}

.is_missing_text <- function(x) {
  is.null(x) || length(x) == 0 || is.na(x) || !nzchar(trimws(as.character(x)))
}

.normalize_text <- function(x, ensure_period = FALSE) {
  x <- as.character(x)
  x <- gsub("[\r\n\t]+", " ", x)
  x <- gsub("\\s+", " ", x)
  x <- trimws(x)
  if (!nzchar(x)) {
    return(NA_character_)
  }
  if (ensure_period && !grepl("[.!?;:]$", x)) {
    x <- paste0(x, ".")
  }
  x
}

.escape_html <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

.folder_species_name <- function(species_name) {
  species_name <- trimws(as.character(species_name))
  species_name <- gsub("\\s+", "_", species_name)
  species_name
}

.slugify <- function(x) {
  x <- iconv(x, from = "", to = "ASCII//TRANSLIT")
  x <- tolower(x)
  x <- gsub("[^a-z0-9]+", "-", x)
  x <- gsub("(^-+|-+$)", "", x)
  x
}

.audio_subtitle_html <- function(audio_ui_strings, lang) {
  subtitle <- audio_ui_strings[[lang]]$subtitle
  generated_with <- audio_ui_strings[[lang]]$generated_with
  date_string <- as.character(Sys.Date())

  paste0(
    .escape_html(subtitle),
    "<br>",
    .escape_html(generated_with), " ",
    '<a href="https://github.com/DBOSlab/aRboretum" target="_blank" rel="noopener noreferrer" class="subtitle-link">aRboretum</a> ',
    .escape_html(date_string),
    "."
  )
}

.get_extra_phrase_text <- function(df, row_index, lang) {
  suffix <- .lang_suffix(lang)
  plant_col <- paste0("plant_uses_", suffix)
  notes_col <- paste0("free_notes_", suffix)

  extras <- character(0)

  if (plant_col %in% names(df)) {
    plant_val <- df[[plant_col]][row_index]
    if (!.is_missing_text(plant_val)) {
      plant_val <- .normalize_text(plant_val, ensure_period = TRUE)
      if (!is.na(plant_val)) {
        extras <- c(extras, plant_val)
      }
    }
  }

  if (notes_col %in% names(df)) {
    notes_val <- df[[notes_col]][row_index]
    if (!.is_missing_text(notes_val)) {
      notes_val <- .normalize_text(notes_val, ensure_period = TRUE)
      if (!is.na(notes_val)) {
        extras <- c(extras, notes_val)
      }
    }
  }

  if (length(extras) == 0) {
    return(NULL)
  }

  paste(extras, collapse = " ")
}

.build_language_buttons <- function(printed_lang,
                                    initial_lang,
                                    lang_button_label) {
  if (length(printed_lang) <= 1L) {
    return("")
  }

  btns <- vapply(printed_lang, function(lang) {
    active <- if (lang == initial_lang) ' class="lang-btn active"' else ' class="lang-btn"'

    label <- unname(lang_button_label[lang])
    if (length(label) == 0 || is.na(label) || !nzchar(trimws(label))) {
      label <- toupper(lang)
    }

    paste0(
      "<button", active, ' data-lang="', lang, '">',
      .escape_html(label),
      "</button>"
    )
  }, character(1))

  paste(btns, collapse = "\n")
}

.build_species_index <- function(df) {
  ids <- vapply(df$taxonName, .slugify, character(1))

  searchable_text <- vapply(seq_len(nrow(df)), function(i) {
    extras <- unlist(df[i, c(
      intersect(
        c(
          "plant_uses_EN", "plant_uses_PT", "plant_uses_FR", "plant_uses_ES",
          "free_notes_EN", "free_notes_PT", "free_notes_FR", "free_notes_ES"
        ),
        names(df)
      )
    )], use.names = FALSE)

    extras <- extras[!is.na(extras) & nzchar(trimws(extras))]
    paste(
      c(df$taxonName[i], df$family[i], extras),
      collapse = " "
    )
  }, character(1))

  links <- paste0(
    '<a class="index-link" data-name="', .escape_html(tolower(searchable_text)), '" href="#', ids, '">',
    .escape_html(df$taxonName),
    "</a>"
  )

  paste(links, collapse = "\n")
}
