#' Generate multilingual HTML labels for plant collections
#'
#' @author
#' Martin Boucknooghe & Domingos Cardoso
#'
#' @description
#' This function generates one standalone HTML label per species for botanical,
#' arboretum, and living plant collections. Each label includes taxonomic
#' information, multilingual species descriptions, browser-based audio playback,
#' interactive distribution maps, optional personal audio recordings, optional
#' personal photos, and institutional or package logos.
#'
#' The function is designed to be used with data generated by `arboretum_data()`.
#' It reads a CSV or Excel file, generates natural-language species descriptions
#' in the selected built-in languages, creates world and Brazil distribution maps,
#' and saves the resulting HTML files to an output directory.
#'
#' In addition to the built-in interface languages (`"pt"`, `"en"`, `"fr"`,
#' and `"es"`), users may supply one extra language through `add_lang`. This
#' extra language is intended as a flexible accessibility pathway for situations
#' where the package interface does not need to be fully translated, but species
#' labels should still include text and optionally audio in a local, Indigenous,
#' or community language.
#'
#' When `add_lang` is supplied and the input data contains non-empty values in the
#' column `full_phrases_ADD_LANGUAGE`, the function adds that extra language as an
#' additional label text option. In this case, the custom language does not pass
#' through the standard phrase-generation and translation workflow. Instead, the
#' content is taken directly from `full_phrases_ADD_LANGUAGE`.
#'
#' When personal audio recordings are available in the expected folder structure,
#' they are embedded in the HTML label and take priority over browser text-to-speech.
#' If no personal recording is available for a given species and language, the label
#' falls back to the browser's speech synthesis engine. When personal photos are
#' available, they are embedded as a slideshow in the species label.
#'
#' @param data_path Required. Character string giving the path to the input data file.
#' The file must be in CSV or Excel format and is typically generated by
#' \code{arboretum_data()}. It should contain, at minimum, the columns
#' \code{taxonName} and \code{family}. Additional columns such as
#' \code{scientificNameAuthorship}, \code{plant_uses_EN}, \code{plant_uses_PT},
#' \code{plant_uses_ES}, \code{plant_uses_FR}, \code{free_notes_EN},
#' \code{free_notes_PT}, \code{free_notes_ES}, \code{free_notes_FR},
#' \code{FFB.url}, \code{POWO.url}, \code{IUCN.status},
#' \code{botanical_country}, \code{introduced_to}, \code{FFB.stateProvince},
#' \code{FFB.establishmentMeans}, and and \code{full_phrases_ADD_LANGUAGE} are
#' used when available. are used when available.
#' @param audio_dir Character string. Directory containing personal audio
#' recordings, usually created with \code{arboretum_audios()}.
#' Default is \code{"arboretum_audios"}. The expected subfolder pattern is
#' \code{FAMILY_Genus_species_LANG}, for example
#' \code{FABACEAE_Paubrasilia_echinata_PT}. Supported audio file extensions are
#' \code{.mp3}, \code{.wav}, \code{.m4a}, \code{.ogg}, \code{.flac} and \code{.webm}.
#' @param photo_dir Character string. Directory containing personal species photos,
#' usually created with \code{arboretum_photos()}. Default is
#' \code{"arboretum_photos"}. The expected subfolder pattern is
#' \code{FAMILY_Genus_species_photos}, for example
#' \code{FABACEAE_Paubrasilia_echinata_photos}. Supported image file extensions
#' include \code{.jpg}, \code{.jpeg}, \code{.png}, \code{.gif}, \code{.webp},
#' \code{.bmp}, and \code{.svg}.
#' @param printed_lang Character vector. Language codes to include in the HTML labels.
#' Accepted values are \code{"pt"} for Portuguese, \code{"en"} for English,
#' \code{"fr"} for French, and \code{"es"} for Spanish. Default is
#' \code{c("pt", "en", "fr", "es")}. The first language in the vector is used as
#' the initial display language.
#' @param add_lang Character string or `NULL`. Optional code for one additional
#' language to include in the labels, for example `"PANARA"` or `"TUKANO"`.
#' This argument is intended for cases where users want to include species text
#' and optional personal audio in a community or local language without translating
#' the entire website or minisite interface. When supplied, and when the input data
#' contains non-empty values in the column `full_phrases_ADD_LANGUAGE`, this extra
#' language is added as an additional text option in the species label. The custom
#' language content is read directly from `full_phrases_ADD_LANGUAGE` rather than
#' being generated by the standard multilingual phrase builder.
#' @param path_to_logo Character string or \code{NULL}. Path to an optional logo image
#' to display in the top-right corner of each label. Supported formats are PNG,
#' JPG/JPEG, GIF, SVG, and WebP. If \code{NULL}, no custom logo is shown.
#' @param logo_url Character string or \code{NULL}. URL to open when the custom logo is
#' clicked. This argument is used only when \code{path_to_logo} is supplied. If
#' \code{NULL}, the logo is displayed without a hyperlink.
#' @param back_to_index Logical. If \code{TRUE}, adds a discrete link below the
#' family name allowing users to return to the minisite index page. Default is
#' \code{TRUE}.
#' @param index_file Character string. Relative path to the minisite index page.
#' Default is \code{"index.html"}. This is usually correct when the species label
#' files and \code{index.html} are in the same folder.
#' @param verbose Logical. If \code{TRUE}, progress messages are printed to the
#' console. Default is \code{TRUE}.
#' @param dir Character string. Output directory where the generated HTML files will
#' be saved. The directory is created if it does not already exist. Default is
#' \code{"arboretum_labels"}.
#'
#' @return
#' Invisibly returns a character vector with the file paths of the generated HTML
#' labels, one file per species. The function is called mainly for its side effects:
#' \itemize{
#' \item creates the output directory, if needed;
#' \item copies non-empty personal audio and photo directories into the output
#' directory;
#' \item generates one HTML label file per species;
#' \item downloads and processes geographic data used for distribution maps;
#' \item removes the temporary WGSRPD folder after label generation.
#' }
#'
#' @details
#' The function follows five main steps:
#'
#' \enumerate{
#' \item \strong{Input preparation}
#' \itemize{
#' \item Validates the output directory and selected languages.
#' \item Creates the output directory if it does not exist.
#' \item Reads the input CSV or Excel file using an internal helper function.
#' }
#'
#' \item \strong{Optional media preparation}
#' \itemize{
#' \item Checks whether the personal audio directory exists and contains files.
#' \item Checks whether the photo directory exists and contains files.
#' \item Copies non-empty personal audio and photo directories into the output
#' directory and renames the copied folders with a double-underscore prefix.
#' \item Ignores empty or missing personal audio and photo directories.
#' }
#'
#' \item \strong{Phrase generation}
#' \itemize{
#' \item Generates species description phrases for each selected built-in language
#' using internal phrase-generation helpers.
#' \item When `add_lang` is supplied and `full_phrases_ADD_LANGUAGE` contains
#' non-empty text, adds one extra language directly from that column.
#' \item This extra language bypasses the standard translation and phrase-generation
#' workflow and is intended for flexible community-based accessibility use cases.
#' \item Adds plant-use and free-note fields to the visible and spoken text when
#' language-specific columns are present and not empty.
#' }
#'
#' \item \strong{Map generation}
#' \itemize{
#' \item Downloads WGSRPD level-3 geographic data for world distribution maps.
#' \item Reads Brazilian state boundaries using \code{geobr::read_state()}.
#' \item Creates an interactive world map using native and introduced distribution
#' information when available.
#' \item Creates a Brazil map when \code{FFB.stateProvince} contains Brazilian
#' state records.
#' }
#'
#' \item \strong{HTML label generation}
#' \itemize{
#' \item Creates one HTML file per species.
#' \item Adds the species name, authorship, family, description text, audio controls,
#' language-switching buttons, distribution maps, source/status icons, package
#' logos, optional custom logo, and optional photo slideshow.
#' \item Embeds available personal audio files and personal photos as data URIs so
#' the generated HTML labels are self-contained.
#' \item Uses browser text-to-speech when personal audio is unavailable.
#' }
#' }
#'
#' Generated file names follow the pattern:
#'
#' \preformatted{
#' FAMILY_Genus_species_label.html
#' }
#'
#' For example:
#'
#' \preformatted{
#' FABACEAE_Paubrasilia_echinata_label.html
#' }
#'
#' Personal audio folders should follow the pattern:
#'
#' \preformatted{
#' FAMILY_Genus_species_LANG
#' }
#'
#' where \code{LANG} is one of \code{PT}, \code{EN}, \code{FR}, \code{ES}, or an
#' additional user-defined language code supplied through `add_lang`.
#'
#' Personal photo folders should follow the pattern:
#'
#' \preformatted{
#' FAMILY_Genus_species_photos
#' }
#'
#' @note
#' \itemize{
#' \item This function requires an internet connection to download WGSRPD geographic
#' data and to retrieve Brazil state boundaries through \pkg{geobr}.
#' \item Browser text-to-speech quality depends on the user's browser, operating
#' system, and installed voices.
#' \item Personal audio recordings take priority over browser text-to-speech when
#' available for a given species and language.
#' \item Only the first audio file found in a species-language audio folder is used.
#' \item Photo slideshows are included only when image files are found in the expected
#' species photo folder.
#' \item The speech rate, pitch, and volume are currently fixed internally in the
#' generated HTML.
#' \item Missing optional columns are ignored when possible, but missing core columns
#' such as \code{taxonName} or \code{family} may cause errors.
#' \item The `add_lang` argument is intended as a flexible, interim solution for
#' adding one extra language to species labels and associated audio, especially in
#' collaborative work with Indigenous peoples or other local communities where full
#' website translation is not necessary or not yet available.
#' \item For custom languages added through `add_lang`, browser text-to-speech may
#' not work reliably unless the user's system provides a compatible voice. Personal
#' recordings are therefore recommended for the extra language whenever possible.
#' }
#'
#' @seealso
#' \code{\link{arboretum_data}},
#' \code{\link{arboretum_audios}},
#' \code{\link{arboretum_photos}}
#'
#' @examples
#' \dontrun{
#' # Generate labels with default settings and all supported languages
#' arboretum_labels(
#' data_path = "arboretum_data/arboretum_data.xlsx"
#' )
#'
#' # Generate labels in Portuguese and English only
#' arboretum_labels(
#' data_path = "arboretum_data/arboretum_data.xlsx",
#' printed_lang = c("pt", "en")
#' )
#'
#' # Add an institutional logo with a clickable URL
#' arboretum_labels(
#' data_path = "arboretum_data/arboretum_data.xlsx",
#' path_to_logo = "path/to/institution_logo.png",
#' logo_url = "https://www.institution.org",
#' dir = "my_arboretum_labels"
#' )
#'
#' # Use personal audio recordings and personal photos
#' arboretum_labels(
#' data_path = "arboretum_data/arboretum_data.xlsx",
#' audio_dir = "arboretum_audios",
#' photo_dir = "arboretum_photos",
#' printed_lang = c("pt", "en", "fr"),
#' verbose = TRUE
#' )
#'
#' # Generate English-only labels without progress messages
#' arboretum_labels(
#' data_path = "arboretum_data/arboretum_data.csv",
#' printed_lang = "en",
#' verbose = FALSE
#' )
#' }
#'
#' @importFrom utils download.file read.csv txtProgressBar unzip
#' @importFrom tools file_ext
#' @importFrom htmltools tags save_html HTML as.tags
#' @importFrom jsonlite toJSON
#' @importFrom dplyr left_join
#' @importFrom tidyr replace_na
#' @importFrom leaflet leaflet addProviderTiles providers setView addPolygons labelOptions
#' @importFrom sf st_read
#' @importFrom geobr read_state
#' @importFrom openxlsx read.xlsx
#' @importFrom magrittr %>%
#' @importFrom htmlwidgets saveWidget
#' @importFrom plotly as_widget
#' @importFrom jpeg readJPEG writeJPEG
#' @importFrom png readPNG writePNG
#'
#' @export

arboretum_labels <- function(data_path = NULL,
                             audio_dir = "arboretum_audios",
                             photo_dir = "arboretum_photos",
                             printed_lang = c("pt", "en", "fr", "es"),
                             add_lang = NULL,
                             path_to_logo = NULL,
                             logo_url = NULL,
                             back_to_index = TRUE,
                             index_file = "index.html",
                             verbose = TRUE,
                             dir = "arboretum_labels"){

  # Validate and clean output directory
  dir <- .arg_check_dir(dir)
  # Validate language vector
  printed_lang <- .arg_check_printed_lang(printed_lang)

  # Create output directory if it does not exist
  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE)
    if (verbose) message("Created directory: ", dir)
  }

  # Copy personal audio folder if it exists and is not empty
  if (dir.exists(audio_dir)) {
    if (length(list.files(audio_dir, recursive = TRUE)) > 0) {
      .copy_folder_progress(from = audio_dir, to = dir, verbose = verbose)
      temp <- paste0(dir, "/__", audio_dir)
      src <- file.path(dir, audio_dir)
      if (dir.exists(src)) {
        file.rename(src, temp)
      } else {
        warning("Source folder to rename not found: ", src)
      }
      audio_dir <- temp
    } else {
      if (verbose) message("Audio folder is empty: ", audio_dir, " - skipping.")
      audio_dir <- NULL
    }
  } else {
    audio_dir <- NULL
  }

  # Copy photo folder if it exists and is not empty
  if (dir.exists(photo_dir)) {
    if (length(list.files(photo_dir, recursive = TRUE)) > 0) {
      .copy_folder_progress(from = photo_dir, to = dir, verbose = verbose)

      temp <- file.path(dir, paste0("__", basename(photo_dir)))
      src <- file.path(dir, basename(photo_dir))

      if (dir.exists(src)) {
        file.rename(src, temp)

        .compress_images_in_dir(
          photo_dir = temp,
          max_size_mb = 1,
          verbose = verbose
        )
      } else {
        warning("Source folder to rename not found: ", src)
      }

      photo_dir <- temp
    } else {
      if (verbose) message("Photo folder is empty: ", photo_dir, " - ignored.")
      photo_dir <- NULL
    }
  } else {
    photo_dir <- NULL
  }

  phrases_out <- .build_arboretum_phrases(
    data_path = data_path,
    printed_lang = printed_lang,
    add_lang = add_lang,
    verbose = verbose
  )

  df <- phrases_out$df
  printed_lang <- phrases_out$printed_lang
  html_phrases <- phrases_out$html_phrases

  output_paths <- character(nrow(df))

  # Get world map of botanical subdivisions (WGSRPD level 3) from internal package data
  WGSRPD <- get("WGSRPD", envir = as.environment("package:aRboretum"))

  # world <- .get_world_map()

  # Get Brazil states map
  br_states <- geobr::read_state(year = 2025,
                                 simplified = FALSE,
                                 showProgress = FALSE,
                                 cache = TRUE)

  # Generate one HTML file per species
  for (i in seq_along(df$taxonName)) {
    output_paths[i] <- .generate_species_html(
      species_data = df[i, , drop = FALSE],
      phrases = html_phrases,
      world = WGSRPD,
      br_states = br_states,
      printed_lang = printed_lang,
      add_lang = add_lang,
      path_to_logo = path_to_logo,
      logo_url = logo_url,
      output_dir = dir,
      audio_dir = audio_dir,
      photo_dir = photo_dir,
      back_to_index = back_to_index,
      index_file = index_file,
      verbose = verbose
    )
  }

  # Clean up temporary WGSRPD folder
  # unlink("WGSRPD", recursive = TRUE)

  if (verbose) {
    message("\nCompleted! Generated ", length(output_paths), " HTML files in: ",
            normalizePath(dir, winslash = "/"))
  }

  invisible(output_paths)
}


# Internal function to compress photos ####
.compress_images_in_dir <- function(photo_dir,
                                    max_size_mb = 1,
                                    verbose = TRUE) {
  if (is.null(photo_dir) || !dir.exists(photo_dir)) {
    return(invisible(character(0)))
  }

  files <- list.files(
    photo_dir,
    recursive = TRUE,
    full.names = TRUE,
    ignore.case = TRUE
  )

  files <- files[grepl("\\.(jpg|jpeg|png)$", files, ignore.case = TRUE)]

  if (length(files) == 0) {
    return(invisible(character(0)))
  }

  compressed <- character(0)

  for (f in files) {
    ok <- tryCatch(
      .compress_single_image(
        path = f,
        max_size_mb = max_size_mb,
        verbose = verbose
      ),
      error = function(e) {
        warning("Could not compress image: ", f, " | ", conditionMessage(e))
        FALSE
      }
    )

    if (isTRUE(ok)) {
      compressed <- c(compressed, f)
    }
  }

  invisible(compressed)
}

.compress_single_image <- function(path,
                                   max_size_mb = 1,
                                   verbose = TRUE) {
  if (!file.exists(path)) {
    return(FALSE)
  }

  size_limit <- max_size_mb * 1024^2
  original_size <- file.info(path)$size

  if (is.na(original_size) || original_size <= size_limit) {
    return(FALSE)
  }

  ext <- tolower(tools::file_ext(path))
  tmp <- tempfile(fileext = paste0(".", ext))

  on.exit({
    if (file.exists(tmp)) {
      unlink(tmp)
    }
  }, add = TRUE)

  img <- .read_image_generic(path, ext)

  if (is.null(img)) {
    warning("Unsupported image format for compression: ", path)
    return(FALSE)
  }

  if (ext %in% c("jpg", "jpeg")) {
    ok <- .compress_jpeg_to_target(
      img = img,
      out_path = tmp,
      size_limit = size_limit
    )
  } else if (ext == "png") {
    ok <- .compress_png_to_target(
      img = img,
      out_path = tmp,
      size_limit = size_limit
    )
  } else {
    return(FALSE)
  }

  if (!ok || !file.exists(tmp)) {
    return(FALSE)
  }

  new_size <- file.info(tmp)$size

  if (is.na(new_size) || new_size >= original_size) {
    return(FALSE)
  }

  file.copy(tmp, path, overwrite = TRUE, copy.mode = TRUE, copy.date = TRUE)

  if (verbose) {
    message(
      "Compressed image: ",
      basename(path),
      " (",
      round(original_size / 1024^2, 2),
      " MB -> ",
      round(new_size / 1024^2, 2),
      " MB)"
    )
  }

  TRUE
}

.read_image_generic <- function(path, ext) {
  if (ext %in% c("jpg", "jpeg")) {
    return(jpeg::readJPEG(path, native = FALSE))
  }

  if (ext == "png") {
    return(png::readPNG(path, native = FALSE))
  }

  NULL
}

.compress_jpeg_to_target <- function(img, out_path, size_limit) {
  qualities <- c(0.85, 0.75, 0.65, 0.55, 0.45, 0.35, 0.25)
  scales <- c(1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4)

  for (scale in scales) {
    img_scaled <- if (scale < 1) .resize_image_array(img, scale) else img

    for (q in qualities) {
      jpeg::writeJPEG(img_scaled, target = out_path, quality = q)

      if (file.exists(out_path) && file.info(out_path)$size <= size_limit) {
        return(TRUE)
      }
    }
  }

  FALSE
}

.compress_png_to_target <- function(img, out_path, size_limit) {
  scales <- c(1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4)

  for (scale in scales) {
    img_scaled <- if (scale < 1) .resize_image_array(img, scale) else img

    png::writePNG(
      image = img_scaled,
      target = out_path,
      compression = 9
    )

    if (file.exists(out_path) && file.info(out_path)$size <= size_limit) {
      return(TRUE)
    }
  }

  FALSE
}

.resize_image_array <- function(img, scale = 1) {
  if (!is.array(img) || length(dim(img)) < 2) {
    stop("`img` must be a 2D or 3D image array.")
  }

  if (!is.numeric(scale) || length(scale) != 1 || scale <= 0 || scale > 1) {
    stop("`scale` must be a single number in (0, 1].")
  }

  dims <- dim(img)
  old_h <- dims[1]
  old_w <- dims[2]

  new_h <- max(1L, as.integer(round(old_h * scale)))
  new_w <- max(1L, as.integer(round(old_w * scale)))

  row_idx <- unique(pmin(old_h, pmax(1L, round(seq(1, old_h, length.out = new_h)))))
  col_idx <- unique(pmin(old_w, pmax(1L, round(seq(1, old_w, length.out = new_w)))))

  if (length(dims) == 2) {
    return(img[row_idx, col_idx, drop = FALSE])
  }

  img[row_idx, col_idx, , drop = FALSE]
}


# Internal function to generate HTML for a single species ####
.generate_species_html <- function(species_data,
                                   phrases,
                                   world,
                                   br_states,
                                   printed_lang,
                                   add_lang,
                                   path_to_logo,
                                   logo_url,
                                   output_dir,
                                   audio_dir = "arboretum_audios",
                                   photo_dir = "arboretum_photos",
                                   back_to_index = TRUE,
                                   index_file = "index.html",
                                   verbose){

  species_name <- species_data$taxonName[1]
  family_name <- species_data$family[1]
  authorship <- species_data$scientificNameAuthorship[1]

  printed_labels <- list()
  visible_distributions <- list()
  spoken_texts <- list()

  # Build labels and texts for each language
  for (lang in printed_lang) {
    printed_labels[[lang]] <- switch(lang,
                                     en = list(title = "Overview of the species",
                                               stop = "Stop",
                                               uses = "Uses",
                                               curi = "Curiosities",
                                               world = "World distribution",
                                               brazil = "Distribution in the states of Brazil",
                                               photos = "Photos",
                                               back_index = "Back to main page"),
                                     pt = list(title = "Apresentação da espécie",
                                               stop = "Parar",
                                               uses = "Usos",
                                               curi = "Curiosidades",
                                               world = "Distribuição global",
                                               brazil = "Distribuição nos estados do Brasil",
                                               photos = "Fotos",
                                               back_index = "Voltar à página principal"),
                                     fr = list(title = "Présentation de l'espèce",
                                               stop = "Arrêter",
                                               uses = "Usages",
                                               curi = "Curiosités",
                                               world = "Distribution mondiale",
                                               brazil = "Distribution dans les États du Brésil",
                                               photos = "Photos",
                                               back_index = "Retour à la page principale"),
                                     es = list(title = "Descripción de la especie",
                                               stop = "Detener",
                                               uses = "Usos",
                                               curi = "Curiosidades",
                                               world = "Distribución mundial",
                                               brazil = "Distribución en los estados de Brasil",
                                               photos = "Fotos",
                                               back_index = "Volver a la página principal")
    )

    if (is.null(add_lang) || lang != add_lang) {
      # Extract plant uses and curiosities from data
      col_uses <- paste0("plant_uses_", toupper(lang))
      uses <- species_data[[col_uses]][1]
      if (is.na(uses)) uses <- ""

      col_curi <- paste0("free_notes_", toupper(lang))
      curi <- species_data[[col_curi]][1]
      if (is.na(curi)) curi <- ""
    } else {
      uses <- ""
      curi <- ""
    }

    extra_html <- ""
    extra_spoken <- ""
    if (nchar(uses) > 0) {
      extra_html <- paste0(extra_html, "<br><br><strong class='section-label'>",
                           printed_labels[[lang]]$uses, ":</strong> ", uses)
      extra_spoken <- paste0(extra_spoken, " ",
                             printed_labels[[lang]]$uses, ": ", uses, ". ")
    }
    if (nchar(curi) > 0) {
      extra_html <- paste0(extra_html, "<br><br><strong class='section-label'>",
                           printed_labels[[lang]]$curi, ":</strong> ", curi)
      extra_spoken <- paste0(extra_spoken,
                             printed_labels[[lang]]$curi, ": ", curi, ". ")
    }

    visible_distributions[[lang]] <- paste0(phrases[[lang]][[species_name]], extra_html)
    clean_text <- gsub("<[^>]*>", "", phrases[[lang]][[species_name]])
    spoken_texts[[lang]] <- paste0(species_name, ". ",
                                   printed_labels[[lang]]$title, ": ",
                                   clean_text, extra_spoken)
  }

  # Load IUCN status icons
  icons_dir <- system.file("figures/iucn_status_spp_icons", package = "aRboretum")
  iucn_img <- NULL
  iucn_status <- species_data$IUCN.status[1]
  if (!is.na(iucn_status) && nzchar(iucn_status)) {
    clean_status <- gsub(".*[(]|[)]$", "", iucn_status)
    filename <- list.files(icons_dir)[grepl(clean_status, list.files(icons_dir))]
    file_path <- file.path(icons_dir, filename)
    if (file.exists(file_path)) {
      icon_src <- .copy_asset_for_html(file_path, output_dir)
      iucn_img <- htmltools::tags$img(src = icon_src,
                                      alt = iucn_status,
                                      title = iucn_status,
                                      style = "height: 24px; width: auto; margin-right: 5px;")
    }
  }

  # FFB and POWO icons with links
  ffb_img <- NULL
  powo_img <- NULL

  ffb_path <- file.path(icons_dir, "ffb_sp_icon.png")
  if (file.exists(ffb_path)) {
    icon_src <- .copy_asset_for_html(ffb_path, output_dir)
    img <- htmltools::tags$img(src = icon_src,
                               alt = "FFB",
                               style = "height: 24px; width: auto; margin-right: 5px;")
    reflora_url <- species_data$FFB.url[1]
    if (!is.na(reflora_url) && nzchar(reflora_url)) {
      ffb_img <- htmltools::tags$a(href = reflora_url,
                                   target = "_blank",
                                   rel = "noopener noreferrer", img)
    }
  }

  powo_path <- file.path(icons_dir, "k_sp_icon.png")
  if (file.exists(powo_path)) {
    icon_src <- .copy_asset_for_html(powo_path, output_dir)
    img <- htmltools::tags$img(src = icon_src,
                               alt = "POWO",
                               style = "height: 24px; width: auto; margin-right: 5px;")
    powo_url <- species_data$POWO.url[1]
    if (!is.na(powo_url) && nzchar(powo_url)) {
      powo_img <- htmltools::tags$a(href = powo_url,
                                    target = "_blank",
                                    rel = "noopener noreferrer", img)
    }
  }

  top_logos <- list()
  if (!is.null(iucn_img)) top_logos <- c(top_logos, list(iucn_img))
  if (!is.null(ffb_img)) top_logos <- c(top_logos, list(ffb_img))
  if (!is.null(powo_img)) top_logos <- c(top_logos, list(powo_img))

  voice_langs <- list(pt = "pt-BR", en = "en-US", fr = "fr-FR", es = "es-ES")

  # Generate distribution maps (Brazil map only if species has occurrences)
  maps <- .mk_map_dist(species_data, world, br_states)
  world_map_html <- .save_map_widget_for_html(
    widget = maps$world_map,
    output_dir = output_dir,
    species_name = species_name,
    map_type = "world"
  )
  brazil_map_html <- .save_map_widget_for_html(
    widget = maps$brazil_map,
    output_dir = output_dir,
    species_name = species_name,
    map_type = "brazil"
  )

  # Create institution logo tag
  logo_tag <- .create_logo_tag(path_to_logo, logo_url, output_dir)

  # Package logos (aRboretum, JBRJ, MMA, Reflora, POWO)
  logo_dir <- system.file("figures", package = "aRboretum")
  logo_config <- list(
    list(file = "aRboretum_hex_sticker.png",
         url = "https://github.com/DBOSlab/aRboretum",
         alt = "aRboretum"),
    list(file = "jbrj_horizontal_logo.png",
         url = "https://www.gov.br/jbrj/pt-br",
         alt = "JBRJ"),
    list(file = "mma.png",
         url = "https://www.gov.br/mma",
         alt = "MMA"),
    list(file = "reflora.png",
         url = "https://reflora.jbrj.gov.br/consulta/#CondicaoTaxonCP",
         alt = "Reflora")
  )
  package_logos <- list()
  for (config in logo_config) {
    file_path <- file.path(logo_dir, config$file)
    if (file.exists(file_path)) {
      icon_src <- .copy_asset_for_html(file_path, output_dir)
      img_tag <- htmltools::tags$img(src = icon_src,
                                     alt = config$alt,
                                     title = paste("Visit", config$alt, "website"),
                                     style = "height: 60px; width: auto; margin: 0 8px;")
      img_tag <- htmltools::tags$a(href = config$url,
                                   target = "_blank",
                                   rel = "noopener noreferrer",
                                   img_tag)
      package_logos <- c(package_logos, list(img_tag))
    }
  }

  # Prepare personal audio data URIs if available
  if (is.null(audio_dir)) {
    js_audio_files <- jsonlite::toJSON(audio_dir, auto_unbox = TRUE)
  } else {
    personal_audios <- .check_personal_audio(species_data, printed_lang, audio_dir)
    audio_files <- list()
    for (lang in printed_lang) {
      if (!is.null(personal_audios[[lang]])) {
        audio_ext <- tools::file_ext(personal_audios[[lang]])
        mime_type <- switch(tolower(audio_ext), mp3 = "audio/mpeg", wav = "audio/wav", m4a = "audio/mp4", ogg = "audio/ogg", flac = "audio/flac", "audio/mpeg")
        audio_files[[lang]] <- .path_for_html(personal_audios[[lang]], output_dir)
      } else {
        audio_files[[lang]] <- NULL
      }
    }
    js_audio_files <- jsonlite::toJSON(audio_files, auto_unbox = TRUE)
  }

  # Build photo slideshow if photos are available
  if (is.null(photo_dir)) {
    slideshow_tag <- NULL
  } else {
    photo_paths <- .check_species_photos(species_data, photo_dir)
    slideshow_tag <- if (length(photo_paths) > 0) {
      slide_items <- lapply(seq_along(photo_paths), function(i) {
        f <- photo_paths[i]
        ext <- tolower(tools::file_ext(f))
        mime <- switch(ext,
                       jpg  = "image/jpeg", jpeg = "image/jpeg",
                       png  = "image/png",  gif  = "image/gif",
                       webp = "image/webp", bmp  = "image/bmp",
                       svg  = "image/svg+xml", "image/jpeg")
        photo_src <- .path_for_html(f, output_dir)
        htmltools::tags$div(
          class = if (i == 1L) "slide active" else "slide",
          htmltools::tags$img(class = "slide__img", src = photo_src,
                              alt = paste("Species photo", i))
        )
      })
      htmltools::tags$div(
        class = "photo-slideshow",
        htmltools::tags$h3(id = "photosTitle", "Photos"),
        htmltools::tags$div(
          id = "slideshow", class = "slideshow",
          slide_items,
          htmltools::tags$button(type = "button",
                                 class = "slideArrow slideArrow--prev",
                                 htmltools::HTML("&#10094;")),
          htmltools::tags$button(type = "button",
                                 class = "slideArrow slideArrow--next",
                                 htmltools::HTML("&#10095;")),
          htmltools::tags$div(
            class = "slideProgress-wrap",
            htmltools::tags$div(id = "slideProgress", class = "slideProgress")
          )
        ),
        htmltools::tags$div(id = "slideDots", class = "slide-dots")
      )
    } else {
      NULL
    }
  }

  # Convert R objects to JSON for JavaScript
  js_printed_labels <- jsonlite::toJSON(printed_labels, auto_unbox = TRUE)
  js_visible_distributions <- jsonlite::toJSON(visible_distributions, auto_unbox = TRUE)
  js_spoken_texts <- jsonlite::toJSON(spoken_texts, auto_unbox = TRUE)
  js_voice_langs <- jsonlite::toJSON(voice_langs, auto_unbox = TRUE)
  js_initial_lang <- jsonlite::toJSON(printed_lang[1], auto_unbox = TRUE)

  # Assemble final HTML page
  page <- .build_html_page(
    species_name = species_name,
    family_name = family_name,
    authorship = authorship,
    logo_tag = logo_tag,
    package_logos = package_logos,
    top_logos = top_logos,
    js_printed_labels = js_printed_labels,
    js_visible_distributions = js_visible_distributions,
    js_spoken_texts = js_spoken_texts,
    js_voice_langs = js_voice_langs,
    js_rate = jsonlite::toJSON(0.95, auto_unbox = TRUE),
    js_pitch = jsonlite::toJSON(1, auto_unbox = TRUE),
    js_volume = jsonlite::toJSON(1, auto_unbox = TRUE),
    js_initial_lang = js_initial_lang,
    js_audio_files = js_audio_files,
    printed_lang = printed_lang,
    world_map_html = world_map_html,
    brazil_map_html = brazil_map_html,
    slideshow_tag = slideshow_tag,
    back_to_index = back_to_index,
    index_file = index_file
  )

  # Save HTML file
  filename <- paste0(toupper(family_name), "_", gsub("\\s", "_", species_name), "_label.html")
  htmltools::save_html(page, file = file.path(output_dir, filename))
  if (verbose) message("Species label file '", filename, "' successfully created!")
  invisible(filename)
}

# Build complete HTML page with CSS, JavaScript, and content ####
.build_html_page <- function(species_name,
                             family_name,
                             authorship,
                             logo_tag,
                             package_logos,
                             js_printed_labels,
                             js_visible_distributions,
                             js_spoken_texts,
                             js_voice_langs,
                             js_rate,
                             js_pitch,
                             js_volume,
                             js_initial_lang,
                             js_audio_files,
                             printed_lang,
                             top_logos = NULL,
                             world_map_html = NULL,
                             brazil_map_html = NULL,
                             slideshow_tag = NULL,
                             back_to_index = TRUE,
                             index_file = "index.html"){

  htmltools::tags$html(
    lang = printed_lang[1],
    htmltools::tags$head(
      htmltools::tags$meta(charset = "UTF-8"),
      htmltools::tags$meta(name = "viewport", content = "width=device-width, initial-scale=1.0"),
      htmltools::tags$title(paste("Species voice card -", species_name)),
      htmltools::tags$style(htmltools::HTML("
        /* CSS styles (same as before) */
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
          max-width: 900px;
          margin: 40px auto;
          padding: 0 24px;
          line-height: 1.6;
          color: #2c3e50;
          background: #fafafa;
        }
        .topbar {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          gap: 20px;
          margin-bottom: 24px;
          padding-bottom: 16px;
          border-bottom: 2px solid #e0e0e0;
        }
        .title-wrapper {
          display: inline-flex;
          flex-wrap: wrap;
          align-items: baseline;
          gap: 0;
          margin-bottom: 8px;
        }
        .species-title {
          margin: 0;
          font-size: 2rem;
          color: #2c5f2d;
          display: inline;
        }
        .authorship {
          font-size: 1.0rem;
          color: #555;
          font-style: normal;
          white-space: nowrap;
          margin-left: 6px;
        }
        .family-name {
          font-variant: small-caps;
          color: green;
          font-size: 1.5rem;
          letter-spacing: 0.5px;
          clear: both;
          margin-top: 4px;
          margin-bottom: 16px;
        }
        .back-index-link {
        display: inline-block;
        margin-top: -8px;
        margin-bottom: 18px;
        color: #8a8a8a;
        font-size: 0.88rem;
        text-decoration: none;
        font-weight: 400;
        }
        .back-index-link:hover {
        color: #2c5f2d;
        text-decoration: underline;
        }
        .logo-box {
          flex-shrink: 0;
          max-width: 200px;
        }
        .logo-box img {
          max-height: 120px;
          width: auto;
        }
        .footer-logos {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #ddd;
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          align-items: center;
          gap: 15px;
        }
        .footer-logos img {
          max-height: 70px;
          width: auto;
          transition: transform 0.2s;
        }
        .footer-logos img:hover {
          transform: scale(1.05);
        }
        .status-logos img {
          height: 32px;
          width: auto;
          vertical-align: middle;
        }
        .controls, .notes-controls {
          margin: 24px 0;
          display: flex;
          flex-wrap: wrap;
          gap: 10px;
          align-items: center;
        }
        .voice-btn, .stop-btn, .lang-btn {
          padding: 10px 18px;
          border: none;
          border-radius: 8px;
          background: #ecf0f1;
          cursor: pointer;
          font-size: 15px;
          font-weight: 500;
          transition: all 0.2s ease;
          color: #2c3e50;
        }
        .voice-btn {
          background: #2c5f2d;
          color: white;
        }
        .voice-btn:hover {
          background: #1e3a1f;
          transform: translateY(-1px);
        }
        .stop-btn:hover, .lang-btn:hover {
          background: #dfe6e9;
          transform: translateY(-1px);
        }
        #spokenPreview {
          margin-top: 24px;
          padding: 16px;
          background: white;
          border-left: 4px solid #2c5f2d;
          border-radius: 4px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          font-size: 1rem;
          line-height: 1.5;
        }
        h3 {
          color: #2c5f2d;
          margin-bottom: 8px;
        }
        .maps-container {
          display: flex;
          gap: 20px;
          flex-wrap: wrap;
          margin-top: 30px;
        }
        .map-box {
          flex: 1;
          min-width: 250px;
        }
        .photo-slideshow {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #e0e0e0;
        }
        .photo-slideshow > h3 {
          color: #2c5f2d;
          margin-bottom: 12px;
        }
        @keyframes kbZoomIn {
          from { transform: scale(1.0); }
          to   { transform: scale(1.12); }
        }
        @keyframes kbZoomOut {
          from { transform: scale(1.12); }
          to   { transform: scale(1.0); }
        }
        @keyframes kbZoomIn2 {
          from { transform: scale(1.0) translateX(0); }
          to   { transform: scale(1.10) translateX(-3%); }
        }
        @keyframes kbZoomOut2 {
          from { transform: scale(1.10) translateX(-3%); }
          to   { transform: scale(1.0) translateX(0); }
        }
        .slideshow {
          position: relative;
          width: 100%;
          height: 440px;
          overflow: hidden;
          border-radius: 8px;
          background: #111;
          box-shadow: 0 2px 10px rgba(0,0,0,0.25);
          user-select: none;
        }
        .slide {
          position: absolute;
          inset: 0;
          opacity: 0;
          transition: opacity 0.9s ease;
          overflow: hidden;
        }
        .slide.active { opacity: 1; z-index: 1; }
        .slide__img {
          width: 100%;
          height: 100%;
          object-fit: contain;
          display: block;
          transform-origin: center center;
        }
        .slideArrow {
          position: absolute;
          top: 50%;
          transform: translateY(-50%);
          z-index: 10;
          background: rgba(0,0,0,0.45);
          color: #fff;
          border: none;
          padding: 10px 15px;
          font-size: 20px;
          cursor: pointer;
          border-radius: 4px;
          line-height: 1;
          transition: background 0.2s;
        }
        .slideArrow:hover { background: rgba(0,0,0,0.75); }
        .slideArrow--prev { left: 10px; }
        .slideArrow--next { right: 10px; }
        .slideProgress-wrap {
          position: absolute;
          bottom: 0; left: 0;
          width: 100%; height: 3px;
          background: rgba(255,255,255,0.2);
          z-index: 10;
        }
        .slideProgress {
          height: 100%;
          width: 0%;
          background: #2c5f2d;
        }
        .slide-dots {
          text-align: center;
          margin-top: 10px;
        }
        .slideDot {
          display: inline-block;
          width: 9px; height: 9px;
          border-radius: 50%;
          background: #ccc;
          margin: 0 4px;
          cursor: pointer;
          border: none;
          padding: 0;
          transition: background 0.2s;
        }
        .slideDot.active { background: #2c5f2d; }
        @media (max-width: 768px) {
          body { padding: 20px 16px; margin: 0; }
          .species-title { font-size: 1.5rem; }
          .authorship { font-size: 0.75rem; }
          .family-name { font-size: 1rem; }
          .controls { gap: 8px; }
          .voice-btn, .stop-btn, .lang-btn { padding: 8px 14px; font-size: 13px; }
          .slideshow { height: 260px; }
        }
      "))
    ),
    htmltools::tags$body(
      htmltools::tags$div(
        class = "topbar",
        htmltools::tags$div(
          style = "flex: 1;",
          htmltools::tags$div(
            class = "title-wrapper",
            htmltools::tags$h1(class = "species-title", htmltools::HTML(paste0("<i>", species_name, "</i>"))),
            htmltools::tags$span(class = "authorship", authorship),
            if (length(top_logos) > 0) {
              htmltools::tags$div(
                class = "status-logos",
                style = "display: inline-flex; align-items: center; gap: 6px; margin-left: 10px;",
                top_logos
              )
            }
          ),
          htmltools::tags$div(class = "family-name", family_name),

          if (isTRUE(back_to_index)) {
            htmltools::tags$a(
              id = "backIndexLink",
              class = "back-index-link",
              href = index_file,
              "Back to main page"
            )
          },
        ),
        if (!is.null(logo_tag)) htmltools::tags$div(class = "logo-box", logo_tag)
      ),
      htmltools::tags$h3(id = "distTitle"),
      htmltools::tags$p(id = "distText", style = "font-size: 1.05rem;"),
      htmltools::tags$div(
        class = "controls",
        htmltools::tags$button(id = "voiceBtn", class = "voice-btn", "🔊 Listen"),
        htmltools::tags$button(id = "stopBtn", class = "stop-btn", "⏹ Stop"),
        lapply(printed_lang, function(lang){
          label <- switch(lang,
                          pt = "Português",
                          en = "English",
                          fr = "Français",
                          es = "Español",
                          toupper(lang))
          htmltools::tags$button(class = "lang-btn", `data-lang` = lang, label)
        })
      ),
      htmltools::tags$div(id = "spokenPreview"),

      # Conditional maps layout: one or two columns
      if (!is.null(world_map_html) && !is.null(brazil_map_html)) {
        htmltools::tags$div(
          class = "maps-container",
          htmltools::tags$div(class = "map-box",
                              htmltools::tags$h3(id = "worldMapTitle"),
                              world_map_html),
          htmltools::tags$div(class = "map-box",
                              htmltools::tags$h3(id = "brazilMapTitle"),
                              brazil_map_html)
        )
      } else if (!is.null(world_map_html)) {
        htmltools::tags$div(style = "margin-top: 30px;",
                            htmltools::tags$h3(id = "worldMapTitle"),
                            world_map_html)
      } else if (!is.null(brazil_map_html)) {
        htmltools::tags$div(style = "margin-top: 30px;",
                            htmltools::tags$h3(id = "brazilMapTitle"),
                            brazil_map_html)
      },
      htmltools::tags$div(
        style = "text-align: center; margin-top: 12px; font-size: 0.85rem;",
        htmltools::tags$span(style = "display: inline-block; margin-right: 20px;",
                             htmltools::tags$span(style = "display: inline-block; width: 14px; height: 14px; background-color: #2c5f2d; margin-right: 5px; border-radius: 2px;"),
                             "Native"
        ),
        htmltools::tags$span(style = "display: inline-block; margin-right: 20px;",
                             htmltools::tags$span(style = "display: inline-block; width: 14px; height: 14px; background-color: #905795; margin-right: 5px; border-radius: 2px;"),
                             "Introduced"
        )
      ),

      slideshow_tag,

      if (length(package_logos) > 0) htmltools::tags$div(class = "footer-logos", package_logos),

      # JavaScript for speech synthesis and language switching
      htmltools::tags$script(htmltools::HTML(sprintf("
    (function() {
      const printedLabels = %s;
      const visibleDistributions = %s;
      const spokenTexts = %s;
      const voiceLangs = %s;
      const audioFiles = %s;
      const rate = %s;
      const pitch = %s;
      const volume = %s;
      const initialLang = %s;

      let currentLang = initialLang;
      let availableVoices = [];
      let currentAudio = null;

      function loadVoices() {
        availableVoices = window.speechSynthesis.getVoices();
        updateVisibleLanguage(currentLang);
      }

      function chooseVoiceForLang(langCode) {
        if (!availableVoices.length) {
          availableVoices = window.speechSynthesis.getVoices();
        }
        let exact = availableVoices.find(v => v.lang === langCode);
        if (exact) return exact;
        const base = langCode.toLowerCase().split('-')[0];
        return availableVoices.find(v => v.lang && v.lang.toLowerCase().startsWith(base)) || null;
      }

      function stopCurrentAudio() {
        if (currentAudio) {
          currentAudio.pause();
          currentAudio.currentTime = 0;
          currentAudio = null;
        }
        window.speechSynthesis.cancel();
      }

      function playPersonalAudio(langKey) {
        const audioDataUri = audioFiles[langKey];
        if (!audioDataUri) return false;
        stopCurrentAudio();
        currentAudio = new Audio(audioDataUri);
        currentAudio.play().catch(error => {
          console.warn('Failed to play personal audio:', error);
          speakCurrentLanguage();
        });
        currentAudio.onended = function() { currentAudio = null; };
        return true;
      }

      function speakCurrentLanguage() {
        if (playPersonalAudio(currentLang)) return;

        const textToSpeak = spokenTexts[currentLang] || spokenTexts[Object.keys(spokenTexts)[0]];
        const langCode = voiceLangs[currentLang];

        if (!langCode) {
        const preview = document.getElementById('spokenPreview');
        if (preview) preview.textContent = textToSpeak || '';
        return;
        }

        stopCurrentAudio();
        const utterance = new SpeechSynthesisUtterance(textToSpeak);
        utterance.lang = langCode;
        utterance.rate = rate;
        utterance.pitch = pitch;
        utterance.volume = volume;

        const voice = chooseVoiceForLang(langCode);
        if (voice) utterance.voice = voice;

        window.speechSynthesis.speak(utterance);
      }

      function updateVisibleLanguage(langKey) {
        const label = printedLabels[langKey] || printedLabels[Object.keys(printedLabels)[0]];
        const visibleText = visibleDistributions[langKey] || visibleDistributions[Object.keys(visibleDistributions)[0]];
        const spokenText = spokenTexts[langKey] || spokenTexts[Object.keys(spokenTexts)[0]];
        currentLang = langKey;
        document.documentElement.lang = langKey;
        const titleEl = document.getElementById('distTitle');
        if (titleEl) titleEl.textContent = label.title;
        const worldMapTitle = document.getElementById('worldMapTitle');
        if (worldMapTitle && label.world) worldMapTitle.textContent = label.world;
        const brazilMapTitle = document.getElementById('brazilMapTitle');
        if (brazilMapTitle && label.brazil) brazilMapTitle.textContent = label.brazil;
        const textEl = document.getElementById('distText');
        if (textEl) textEl.innerHTML = visibleText;
        const previewEl = document.getElementById('spokenPreview');
        if (previewEl) previewEl.textContent = spokenText;
        const stopBtn = document.getElementById('stopBtn');
        if (stopBtn) stopBtn.textContent = label.stop;
        const photosTitleEl = document.getElementById('photosTitle');
        if (photosTitleEl && label.photos) photosTitleEl.textContent = label.photos;
        const backIndexLink = document.getElementById('backIndexLink');
        if (backIndexLink && label.back_index) {
        backIndexLink.textContent = label.back_index;
        }
        const voiceBtn = document.getElementById('voiceBtn');
        if (voiceBtn) {
          const hasAudio = !!audioFiles[langKey];
          const hasTts = !!voiceLangs[langKey];
          if (hasAudio) {
            voiceBtn.textContent = '🎵 Listen (Personal Recording)';
          } else if (hasTts) {
            voiceBtn.textContent = '🔊 Listen';
          } else {
            voiceBtn.textContent = '📖 Text only';
          }
        }
      }

      document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', function() {
          updateVisibleLanguage(btn.dataset.lang);
        });
      });
      const voiceBtn = document.getElementById('voiceBtn');
      if (voiceBtn) voiceBtn.addEventListener('click', speakCurrentLanguage);
      const stopBtn = document.getElementById('stopBtn');
      if (stopBtn) stopBtn.addEventListener('click', stopCurrentAudio);

      if (typeof window.speechSynthesis !== 'undefined') {
        window.speechSynthesis.onvoiceschanged = loadVoices;
        loadVoices();
      }
      updateVisibleLanguage(initialLang);
    })();
  ",
                                                     js_printed_labels, js_visible_distributions, js_spoken_texts,
                                                     js_voice_langs, js_audio_files, js_rate, js_pitch, js_volume, js_initial_lang
      ))),

      # JavaScript for Ken Burns slideshow
      htmltools::tags$script(htmltools::HTML('
    (function() {
      const KB = ["kbZoomIn", "kbZoomOut", "kbZoomIn2", "kbZoomOut2"];
      const slideshow = document.getElementById("slideshow");
      if (!slideshow) return;

      const slides = Array.from(slideshow.querySelectorAll(".slide"));
      if (slides.length === 0) return;

      const dotsWrap = document.getElementById("slideDots");
      const progressEl = document.getElementById("slideProgress");
      const INTERVAL = 5000;
      let current = 0, timer = null;
      let lastKb = -1;

      if (dotsWrap && dotsWrap.children.length === 0) {
        slides.forEach((_, i) => {
          const d = document.createElement("button");
          d.className = "slideDot" + (i === 0 ? " active" : "");
          d.setAttribute("aria-label", "Slide " + (i + 1));
          d.type = "button";
          d.addEventListener("click", () => { goTo(i); resetTimer(); });
          dotsWrap.appendChild(d);
        });
      }

      function applyKenBurns(slideEl) {
        const img = slideEl.querySelector(".slide__img");
        if (!img) return;
        img.style.animation = "none";
        void img.offsetWidth;
        let pick;
        do { pick = Math.floor(Math.random() * KB.length); } while (pick === lastKb);
        lastKb = pick;
        img.style.animation = KB[pick] + " 8s ease-in-out forwards";
      }

      function updateDots(i) {
        if (!dotsWrap) return;
        Array.from(dotsWrap.querySelectorAll(".slideDot")).forEach((d, j) => {
          d.classList.toggle("active", j === i);
        });
      }

      function startProgress() {
        if (!progressEl) return;
        progressEl.classList.remove("running");
        progressEl.style.transition = "none";
        progressEl.style.width = "0%";
        void progressEl.offsetWidth;
        progressEl.style.transition = "width " + INTERVAL + "ms linear";
        progressEl.classList.add("running");
        progressEl.style.width = "100%";
      }

      function goTo(idx) {
        slides[current].classList.remove("active");
        current = (idx + slides.length) % slides.length;
        slides[current].classList.add("active");
        applyKenBurns(slides[current]);
        updateDots(current);
        startProgress();
      }

      function resetTimer() {
        if (timer) clearInterval(timer);
        timer = setInterval(() => goTo(current + 1), INTERVAL);
      }

      const prevBtn = slideshow.querySelector(".slideArrow--prev");
      const nextBtn = slideshow.querySelector(".slideArrow--next");

      if (prevBtn) prevBtn.addEventListener("click", () => { goTo(current - 1); resetTimer(); });
      if (nextBtn) nextBtn.addEventListener("click", () => { goTo(current + 1); resetTimer(); });

      if (slides.length <= 1) {
        if (prevBtn) prevBtn.style.display = "none";
        if (nextBtn) nextBtn.style.display = "none";
        if (dotsWrap) dotsWrap.style.display = "none";
      }

      slideshow.addEventListener("mouseenter", () => { if (timer) clearInterval(timer); });
      slideshow.addEventListener("mouseleave", resetTimer);

      let touchStart = 0;
      slideshow.addEventListener("touchstart", e => { touchStart = e.touches[0].clientX; }, { passive: true });
      slideshow.addEventListener("touchend", e => {
        const diff = e.changedTouches[0].clientX - touchStart;
        if (Math.abs(diff) > 40) {
          diff < 0 ? goTo(current + 1) : goTo(current - 1);
          resetTimer();
        }
      });

      goTo(0);
      resetTimer();
    })();
  '))
    )
  )
}

# Generate distribution maps (world and conditional Brazil) ####
.mk_map_dist <- function(df_sp = NULL, world, br_states){
  world_plant <- .get_pr_ab_world(df_sp, world)
  p_world <- .ggplot_map(world_plant)

  # Only create Brazil map if species has occurrences in Brazilian states
  if (!is.na(df_sp$FFB.stateProvince) && nzchar(df_sp$FFB.stateProvince)) {
    br_plant <- .get_pr_ab_br(df_sp, br_states)
    if (any(br_plant$Freq > 0, na.rm = TRUE)) {
      p_br <- .ggplot_map_br(br_plant, df_sp)
      return(list(world_map = p_world, brazil_map = p_br))
    }
  }
  return(list(world_map = p_world))
}

.check_species_photos <- function(species_data,
                                  photo_dir = "arboretum_photos") {
  species_name <- gsub("\\s", "_", species_data$taxonName[1])
  family_name <- toupper(species_data$family[1])
  folder_name <- file.path(photo_dir, paste(family_name, species_name, "photos", sep = "_"))
  if (!dir.exists(folder_name)) return(character(0))
  img_pattern <- "\\.(jpg|jpeg|png|gif|webp|bmp|svg)$"
  list.files(folder_name, pattern = img_pattern, ignore.case = TRUE, full.names = TRUE)
}

.check_personal_audio <- function(species_data,
                                  printed_lang,
                                  audio_dir = "arboretum_audios"){
  species_name <- gsub("\\s", "_", species_data$taxonName[1])
  family_name <- toupper(species_data$family[1])
  audio_files <- list()
  for (lang in printed_lang) {
    lang_code <- toupper(lang)
    folder_name <- file.path(audio_dir, paste(family_name, species_name, lang_code, sep = "_"))
    if (dir.exists(folder_name)) {
      audio_extensions <- c("\\.mp3$", "\\.wav$", "\\.m4a$", "\\.ogg$", "\\.flac$", "\\.webm$")
      pattern <- paste(audio_extensions, collapse = "|")
      audio_file <- list.files(folder_name, pattern = pattern, ignore.case = TRUE, full.names = TRUE)
      if (length(audio_file) > 0) audio_files[[lang]] <- audio_file[1]
      else audio_files[[lang]] <- NULL
    } else {
      audio_files[[lang]] <- NULL
    }
  }
  return(audio_files)
}


.copy_asset_for_html <- function(file_path, output_dir, asset_dir = "__assets"){
  if (is.null(file_path) || !nzchar(file_path)) return(NULL)
  if (!file.exists(file_path)) stop("Asset file not found: ", file_path, call. = FALSE)
  asset_root <- file.path(output_dir, asset_dir)
  if (!dir.exists(asset_root)) dir.create(asset_root, recursive = TRUE, showWarnings = FALSE)
  dest <- file.path(asset_root, basename(file_path))
  if (!file.exists(dest)) file.copy(file_path, dest, overwrite = TRUE)
  file.path(asset_dir, basename(file_path))
}

.path_for_html <- function(file_path, output_dir){
  if (is.null(file_path) || !nzchar(file_path)) return(NULL)
  output_dir_norm <- normalizePath(output_dir, winslash = "/", mustWork = FALSE)
  file_path_norm <- normalizePath(file_path, winslash = "/", mustWork = FALSE)
  prefix <- paste0(output_dir_norm, "/")
  if (startsWith(file_path_norm, prefix)) {
    return(substring(file_path_norm, nchar(prefix) + 1L))
  }
  basename(file_path_norm)
}

.save_map_widget_for_html <- function(widget,
                                      output_dir,
                                      species_name,
                                      map_type = c("world", "brazil")){
  if (is.null(widget)) return(NULL)
  map_type <- match.arg(map_type)

  maps_dir <- file.path(output_dir, "__maps")
  if (!dir.exists(maps_dir)) dir.create(maps_dir, recursive = TRUE, showWarnings = FALSE)

  slug <- gsub("[^A-Za-z0-9]+", "_", species_name)
  slug <- gsub("^_+|_+$", "", slug)
  file_name <- paste0(slug, "_", map_type, "_map.html")
  map_file <- file.path(maps_dir, file_name)

  htmlwidgets::saveWidget(
    widget = plotly::as_widget(widget),
    file = map_file,
    selfcontained = FALSE,
    libdir = "libs"
  )

  htmltools::tags$iframe(
    src = file.path("__maps", file_name),
    title = paste(toupper(substr(map_type, 1, 1)), substring(map_type, 2), "map for", species_name),
    loading = "lazy",
    style = paste(
      "width: 100%;",
      "height: 420px;",
      "border: none;",
      "border-radius: 10px;",
      "background: #fff;"
    )
  )
}


.create_logo_tag <- function(path_to_logo, logo_url, output_dir){
  if (is.null(path_to_logo)) return(NULL)
  if (!file.exists(path_to_logo)) stop("Logo file not found: ", path_to_logo, call. = FALSE)
  ext <- tolower(tools::file_ext(path_to_logo))
  switch(ext,
         png = , jpg = , jpeg = , gif = , svg = , webp = NULL,
         stop("Unsupported logo format."))
  logo_src <- .copy_asset_for_html(path_to_logo, output_dir)
  img_tag <- htmltools::tags$img(src = logo_src, style = "height: 300px; width: auto; display: block;")
  if (!is.null(logo_url) && nzchar(logo_url)) {
    return(htmltools::tags$a(href = logo_url, target = "_blank", rel = "noopener noreferrer", img_tag))
  }
  return(img_tag)
}

# .get_world_map <- function(){
#   download.file(url = "https://github.com/tdwg/wgsrpd/archive/master.zip",
#                 destfile = "wgsrpd-master.zip")
#   unzip("wgsrpd-master.zip")
#   unlink("wgsrpd-master.zip")
#   file.rename("wgsrpd-master", "WGSRPD")
#   unlink(c("WGSRPD/level1", "WGSRPD/level2", "WGSRPD/level4", "WGSRPD/geojson"),
#          recursive = TRUE)
#   file.rename("WGSRPD/README.md", "WGSRPD/README.txt")
#   world <- sf::st_read("WGSRPD/level3/level3.shp")
#   world <- world[!world$LEVEL3_NAM %in% "Antarctica", ]
#   world$LEVEL3_NAM[367] <- "DR Congo"
#   world$LEVEL3_NAM[306] <- "Sudan-South Sudan"
#
#   return(world)
# }

.mk_map_dist <- function(df_sp = NULL, world, br_states){
  world_plant <- .get_pr_ab_world(df_sp, world)
  p_world <- .ggplot_map(world_plant)
  if (!is.na(df_sp$FFB.stateProvince)) {
    br_plant <- .get_pr_ab_br(df_sp, br_states)
    p_br <- .ggplot_map_br(br_plant, df_sp)
    return(list(world_map = p_world, brazil_map = p_br))
  } else {
    return(list(world_map = p_world))
  }
}

.get_pr_ab_world <- function(df_sp, world){
  native_string <- df_sp$botanical_country
  if (is.na(native_string) || native_string == "" || native_string == "NA") {
    country_counts <- data.frame(LEVEL3_NAM = character(0), Freq_Native = integer(0))
  } else {
    country_data <- strsplit(native_string, "\\s[|]\\s")[[1]]
    country_data <- country_data[!grepl("[|]", country_data) & !is.na(country_data)]
    if (length(country_data) > 0) {
      country_counts <- data.frame(table(country_data))
      names(country_counts) <- c("LEVEL3_NAM", "Freq_Native")
    } else {
      country_counts <- data.frame(LEVEL3_NAM = character(0), Freq_Native = integer(0))
    }
  }
  introduced_string <- df_sp$introduced_to
  if (is.na(introduced_string) || introduced_string == "" || introduced_string == "NA") {
    introduced_counts <- data.frame(LEVEL3_NAM = character(0), Freq_Introduced = integer(0))
  } else {
    introduced_data <- strsplit(introduced_string, "\\s[|]\\s")[[1]]
    introduced_data <- introduced_data[!grepl("[|]", introduced_data) & !is.na(introduced_data)]
    if (length(introduced_data) > 0) {
      introduced_counts <- data.frame(table(introduced_data))
      names(introduced_counts) <- c("LEVEL3_NAM", "Freq_Introduced")
    } else {
      introduced_counts <- data.frame(LEVEL3_NAM = character(0), Freq_Introduced = integer(0))
    }
  }
  world_plant <- world
  if (nrow(country_counts) > 0) {
    world_plant <- dplyr::left_join(world_plant, country_counts, by = "LEVEL3_NAM")
    world_plant$Freq_Native[is.na(world_plant$Freq_Native)] <- 0
  } else {
    world_plant$Freq_Native <- 0
  }
  if (nrow(introduced_counts) > 0) {
    world_plant <- dplyr::left_join(world_plant, introduced_counts, by = "LEVEL3_NAM")
    world_plant$Freq_Introduced[is.na(world_plant$Freq_Introduced)] <- 0
  } else {
    world_plant$Freq_Introduced <- 0
  }
  if (!"Freq_Native" %in% names(world_plant)) world_plant$Freq_Native <- 0
  if (!"Freq_Introduced" %in% names(world_plant)) world_plant$Freq_Introduced <- 0
  return(world_plant)
}

.get_pr_ab_br <- function(df_sp, br_states){
  states <- strsplit(df_sp$FFB.stateProvince, "\\s[|]\\s")[[1]]
  states <- states[!grepl("[|]", states)]
  states_data <- data.frame(table(states))
  names(states_data) <- c("abbrev_state", "Freq")
  br_plant <- dplyr::left_join(br_states, states_data, by = "abbrev_state")
  br_plant$Freq <- tidyr::replace_na(br_plant$Freq, 0)
  br_plant$hover_text <- ifelse(br_plant$Freq == 1, as.character(br_plant$name_state), "")
  br_plant
}

.ggplot_map <- function(world_plant){
  if (is.null(world_plant) || nrow(world_plant) == 0) return(NULL)
  world_plant$hover_text <- ifelse(world_plant$Freq_Native == 1 | world_plant$Freq_Introduced == 1,
                                   as.character(world_plant$LEVEL3_NAM), "")
  highlight_country_data <- NULL
  highlight_introduced_data <- NULL

  if ("Freq_Native" %in% names(world_plant)) {
    highlight_country_data <- world_plant[world_plant$Freq_Native == 1 & !is.na(world_plant$Freq_Native), ]
  }

  if ("Freq_Introduced" %in% names(world_plant)) {
    highlight_introduced_data <- world_plant[world_plant$Freq_Introduced == 1 & !is.na(world_plant$Freq_Introduced), ]
  }
  map <- leaflet::leaflet() %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    leaflet::setView(lng = 0, lat = 20, zoom = 2)

  map <- leaflet::addPolygons(map,
                              data = world_plant,
                              fillColor = "#ecf0f1",
                              fillOpacity = 0.7,
                              weight = 0.8, color = "black",
                              opacity = 0.6,
                              label = ~hover_text,
                              labelOptions = leaflet::labelOptions(style = list("font-size" = "12px"),
                                                                   opacity = 0.8))

  if (!is.null(highlight_country_data) && nrow(highlight_country_data) > 0) {
    map <- leaflet::addPolygons(map,
                                data = highlight_country_data,
                                fillColor = "#2c5f2d",
                                fillOpacity = 0.8,
                                weight = 0.8,
                                color = "black",
                                opacity = 0.8,
                                label = ~LEVEL3_NAM,
                                labelOptions = leaflet::labelOptions(style = list("font-size" = "12px",
                                                                                  "font-weight" = "bold"),
                                                                     opacity = 0.9))
  }
  if (!is.null(highlight_introduced_data) && nrow(highlight_introduced_data) > 0) {
    map <- leaflet::addPolygons(map,
                                data = highlight_introduced_data,
                                fillColor = "#905795",
                                fillOpacity = 0.8,
                                weight = 0.8,
                                color = "black",
                                opacity = 0.8,
                                label = ~LEVEL3_NAM,
                                labelOptions = leaflet::labelOptions(style = list("font-size" = "12px",
                                                                                  "font-weight" = "bold"),
                                                                     opacity = 0.9))
  }
  return(map)
}

.ggplot_map_br <- function(br_plant, df_sp){
  if (is.null(br_plant) || nrow(br_plant) == 0)
    return(NULL)
  if (!"name_state" %in% names(br_plant)) {
    warning("Column 'name_state' not found in Brazil data")
    return(NULL)
  }

  br_plant$hover_text <- ifelse(br_plant$Freq == 1,
                                as.character(br_plant$name_state),
                                "")
  highlight_data <- br_plant[br_plant$Freq == 1 & !is.na(br_plant$Freq), ]

  map <- leaflet::leaflet() %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    leaflet::setView(lng = -55, lat = -15, zoom = 4)

  map <- leaflet::addPolygons(map,
                              data = br_plant,
                              fillColor = "#ecf0f1",
                              fillOpacity = 0.7, weight = 1.2,
                              color = "black", opacity = 0.7,
                              label = ~hover_text,
                              labelOptions = leaflet::labelOptions(style = list("font-size" = "12px"),
                                                                   opacity = 0.8))

  if (!is.null(highlight_data) && nrow(highlight_data) > 0) {

    fill_col <- if (df_sp$FFB.establishmentMeans == "Native") "#2c5f2d"
    else "#905795"

    map <- leaflet::addPolygons(map,
                                data = highlight_data,
                                fillColor = fill_col,
                                fillOpacity = 0.85,
                                weight = 1.5,
                                color = "black",
                                opacity = 0.9,
                                label = ~name_state,
                                labelOptions = leaflet::labelOptions(style = list("font-size" = "12px",
                                                                                  "font-weight" = "bold"),
                                                                     opacity = 0.9))
  }
  return(map)
}
