#' Build a multilingual minisite index for generated species labels
#'
#' @author
#' Domingos Cardoso & Martin Boucknooghe
#'
#' @description
#' This function builds a standalone multilingual HTML index page for species
#' labels generated by \code{arboretum_labels()}. It scans a directory containing
#' \code{_label.html} files, extracts family and species names from the filenames,
#' and creates a searchable index with direct links to each individual species
#' label.
#'
#' When a mined-data file from \code{arboretum_data()} is supplied through
#' \code{data_path}, the minisite also displays vernacular names on species cards
#' and includes an interactive summary dashboard with collection-level statistics.
#' The generated page supports Portuguese, English, French, and Spanish interface
#' text according to the languages selected in \code{printed_lang}.
#'
#' The resulting \code{index.html} is first saved inside \code{labels_dir}. After
#' the index is written, the entire labels directory is renamed using
#' \code{site_title}, converted to ASCII and with spaces replaced by underscores,
#' followed by the suffix \code{_minisite}.
#'
#' @param labels_dir Character string. Path to the directory containing the HTML
#' label files produced by \code{arboretum_labels()}. The directory must exist
#' and must contain files ending in \code{_label.html}.
#' @param data_path Character string or \code{NULL}. Optional path to the CSV or
#' Excel file produced by \code{arboretum_data()}, usually the same file
#' used to generate the species labels. When supplied and successfully read,
#' vernacular names are added to species cards, the search box also searches
#' vernacular names, and the dashboard is rendered. If the file cannot be read,
#' the function proceeds without vernacular names and without the dashboard.
#' Default is \code{NULL}.
#' @param output_file Character string or \code{NULL}. Full path for the output
#' index HTML file. If \code{NULL}, the file is written as \code{index.html}
#' inside \code{labels_dir}. If supplied, the parent directory must already exist.
#' Default is \code{NULL}.
#' @param site_title Character string. Title displayed in the browser tab and page
#' header. It is also used to rename the final minisite folder after
#' \code{index.html} is written. Default is \code{"Plant Collection"}.
#' @param printed_lang Character vector. Language codes to include in the minisite
#' interface. Accepted values are \code{"pt"} for Portuguese, \code{"en"} for
#' English, \code{"fr"} for French, and \code{"es"} for Spanish. The first
#' language in the vector sets the initial display language. Default is
#' \code{c("pt", "en", "fr", "es")}.
#' @param group_by_family Logical. If \code{TRUE}, species cards are grouped under
#' family headings. If \code{FALSE}, all species cards are shown in a single flat
#' grid. Default is \code{TRUE}.
#' @param logo Character string or \code{NULL}. Optional path to a logo image to
#' embed in the minisite header as a Base64 data URI. Supported formats are PNG,
#' JPG/JPEG, SVG, and WebP. If \code{NULL}, no logo is shown. Default is
#' \code{NULL}.
#' @param logo_url Character string or \code{NULL}. Optional URL to open when the
#' logo is clicked. Used only when \code{logo} is supplied. If \code{NULL}, the
#' logo is displayed without a hyperlink. Default is \code{NULL}.
#' @param verbose Logical. If \code{TRUE}, prints a summary message after saving
#' the minisite index and renaming the labels directory. Default is \code{TRUE}.
#'
#' @return
#' Invisibly returns the path used to write the index HTML file. The function is
#' called mainly for its side effects:
#' \itemize{
#' \item scans \code{labels_dir} for \code{_label.html} files;
#' \item writes a multilingual \code{index.html} file;
#' \item optionally embeds a logo as a Base64 data URI;
#' \item optionally reads mined species data to add vernacular names and dashboard
#' summaries;
#' \item renames the labels directory using the sanitized \code{site_title} plus
#' the suffix \code{_minisite}.
#' }
#'
#' @details
#' The function follows five main steps:
#'
#' \enumerate{
#' \item \strong{Input validation}
#' \itemize{
#' \item Checks that \code{labels_dir} exists.
#' \item Searches for files ending in \code{_label.html}.
#' \item Checks that \code{site_title} is a single non-empty character string.
#' \item Validates the selected interface languages.
#' \item Checks that the parent directory of \code{output_file} exists, when
#' \code{output_file} is supplied.
#' }
#'
#' \item \strong{Optional mined-data loading}
#' \itemize{
#' \item Reads the file supplied through \code{data_path}, when provided.
#' \item Uses the mined data to join vernacular names to the species cards.
#' \item Uses the mined data to compute dashboard statistics.
#' \item Continues without a dashboard if the file cannot be read.
#' }
#'
#' \item \strong{Filename parsing}
#' \itemize{
#' \item Parses label filenames following the pattern
#' \code{FAMILY_Genus_species_label.html}.
#' \item Treats the first underscore-separated token as the family.
#' \item Joins the remaining tokens as the species name.
#' \item Handles species names with more than two epithet tokens, provided they
#' follow the same filename convention.
#' }
#'
#' \item \strong{HTML minisite construction}
#' \itemize{
#' \item Builds a searchable species index.
#' \item Adds real-time filtering by species, family, and vernacular name when
#' vernacular names are available.
#' \item Adds language-switching buttons when more than one language is supplied.
#' \item Groups species by family when \code{group_by_family = TRUE}.
#' \item Adds a footer linking to \code{aRboretum}.
#' }
#'
#' \item \strong{Dashboard construction}
#' \itemize{
#' \item Builds summary cards for total species, genera, and families.
#' \item Builds an origin donut chart from \code{FFB.establishmentMeans}.
#' \item Builds a Brazilian state bar chart from \code{FFB.stateProvince}.
#' \item Builds a phytogeographic-domain donut chart from
#' \code{FFB.phytogeographicDomain}.
#' \item Builds a world-distribution bar chart from \code{country}.
#' \item Dynamically translates dashboard headings and labels when the interface
#' language is changed.
#' }
#' }
#'
#' The dashboard requires columns from the mined-data file, especially
#' \code{taxonName}, \code{family}, \code{FFB.vernacularName},
#' \code{FFB.establishmentMeans}, \code{FFB.stateProvince},
#' \code{FFB.phytogeographicDomain}, and \code{country}. Missing optional values may
#' simply result in empty or omitted dashboard panels.
#'
#' @note
#' \itemize{
#' \item The function expects label filenames produced by \code{arboretum_labels()}.
#' \item The minisite links are relative links to the individual species label files.
#' \item The function renames \code{labels_dir} after writing the index. For example,
#' \code{site_title = "JBRJ Arboretum"} renames the folder to
#' \code{JBRJ_Arboretum_minisite}.
#' \item Because the directory is renamed after writing, users should open the final
#' \code{index.html} inside the renamed minisite folder.
#' \item Existing folders with the same final minisite name may cause
#' \code{file.rename()} to fail, depending on the operating system.
#' \item The output is a standalone HTML file, but it links to the separate species
#' label HTML files in the same folder.
#' }
#'
#' @seealso
#' \code{\link{arboretum_data}},
#' \code{\link{arboretum_labels}}
#'
#' @examples
#' \dontrun{
#' # Build a minisite index from a folder of generated labels
#' arboretum_minisite(
#' labels_dir = "arboretum_species_labels"
#' )
#'
#' # Build a minisite with vernacular names and dashboard summaries
#' arboretum_minisite(
#' labels_dir = "arboretum_species_labels",
#' data_path = "arboretum_data/arboretum_data.xlsx"
#' )
#'
#' # Portuguese and English interface, flat species grid, custom title
#' arboretum_minisite(
#' labels_dir = "arboretum_species_labels",
#' data_path = "arboretum_data/arboretum_data.xlsx",
#' site_title = "JBRJ Arboretum",
#' printed_lang = c("pt", "en"),
#' group_by_family = FALSE
#' )
#'
#' # Add a clickable institutional logo
#' arboretum_minisite(
#' labels_dir = "arboretum_species_labels",
#' data_path = "arboretum_data/arboretum_data.xlsx",
#' site_title = "Plant Collection",
#' logo = "path/to/logo.png",
#' logo_url = "https://www.institution.org"
#' )
#' }
#'
#' @importFrom tools file_ext
#' @importFrom base64enc dataURI
#' @importFrom jsonlite toJSON
#' @importFrom stringi stri_trans_general
#'
#' @export

arboretum_minisite <- function(labels_dir = NULL,
                               data_path = NULL,
                               output_file = NULL,
                               site_title = "Plant Collection",
                               printed_lang = c("pt", "en", "fr", "es"),
                               group_by_family = TRUE,
                               logo = NULL,
                               logo_url = NULL,
                               verbose = TRUE){

  # ---- Validate inputs -------------------------------------------------------

  if (!dir.exists(labels_dir))
    stop("Directory not found: ", labels_dir, call. = FALSE)

  html_files <- list.files(labels_dir, pattern = "_label\\.html$",
                           full.names = FALSE)
  if (length(html_files) == 0L)
    stop("No '*_label.html' files found in: ", labels_dir,
         "\nRun arboretum_labels() first.", call. = FALSE)

  if (!is.character(site_title) || length(site_title) != 1L || !nzchar(site_title))
    stop("'site_title' must be a single non-empty character string.", call. = FALSE)

  printed_lang <- .arg_check_printed_lang(printed_lang)

  if (!is.null(output_file)) {
    if (!dir.exists(dirname(output_file)))
      stop("Output directory does not exist: ", dirname(output_file), call. = FALSE)
  } else {
    output_file <- file.path(labels_dir, "index.html")
  }

  # ---- Load mined data (optional) --------------------------------------------

  mined_df <- NULL
  if (!is.null(data_path)) {
    mined_df <- tryCatch(
      .read_species_data(data_path, verbose = FALSE),
      error = function(e){
        warning("Could not load data_path: ", e$message,
                "\nProceeding without vernacular names and dashboard.",
                call. = FALSE)
        NULL
      }
    )
  }

  # ---- Embed logo ------------------------------------------------------------

  logo_data_uri <- NULL
  if (!is.null(logo)) {
    if (!file.exists(logo)) stop("Logo file not found: ", logo, call. = FALSE)
    ext <- tolower(tools::file_ext(logo))
    mime_type <- switch(ext,
                        png = "image/png", jpg = "image/jpeg", jpeg = "image/jpeg",
                        svg = "image/svg+xml", webp = "image/webp",
                        stop("Unsupported logo format '", ext, "'.", call. = FALSE))
    logo_data_uri <- base64enc::dataURI(file = logo, mime = mime_type)
  }

  # ---- Parse filenames + join ALL vernacular names ---------------------------

  species_df <- .parse_label_filenames(html_files, mined_df)

  # ---- Build and save HTML ---------------------------------------------------

  html_content <- .build_minisite_html(
    species_df = species_df,
    mined_df = mined_df,
    site_title = site_title,
    printed_lang = printed_lang,
    logo_data_uri = logo_data_uri,
    logo_url = logo_url,
    group_by_family = group_by_family
  )

  writeLines(html_content, con = output_file, useBytes = TRUE)

  site_title <- stringi::stri_trans_general(site_title,
                                            "Latin-ASCII")
  site_title <- paste0(gsub("\\s", "_", site_title), "_minisite")
  file.rename(labels_dir, site_title)

  if (verbose) {
    message(
      "Minisite index '", basename(output_file), "' created: ",
      nrow(species_df), " species across ",
      length(unique(species_df$family)), " ",
      if (length(unique(species_df$family)) == 1L) "family" else "families",
      " [", paste(printed_lang, collapse = "/"), "].\n"
    )
    message("\nThe original species labels folder '",
            labels_dir, "' was renamed as '", gsub("\\s", "_", site_title), "'")
  }

  invisible(output_file)
}

# ==============================================================================
# Parse filenames; join ALL vernacular names (full pipe-separated string)
# ==============================================================================
.parse_label_filenames <- function(html_files, mined_df = NULL){
  parsed <- lapply(html_files, function(f) {
    stem <- sub("_label\\.html$", "", f)
    parts <- strsplit(stem, "_", fixed = TRUE)[[1L]]
    fam <- parts[1L]
    spp <- paste(parts[-1L], collapse = " ")

    vern <- ""
    if (!is.null(mined_df)) {
      idx <- which(toupper(mined_df$family) == fam & mined_df$taxonName == spp)
      if (length(idx) > 0L) {
        raw <- mined_df$FFB.vernacularName[idx[1L]]
        if (!is.na(raw) && nzchar(trimws(raw))) {
          # Keep ALL names exactly as in the source, just normalise spacing
          parts_v <- trimws(strsplit(raw, "\\s*\\|\\s*")[[1L]])
          parts_v <- parts_v[nzchar(parts_v)]
          if (length(parts_v) > 0L)
            vern <- paste(parts_v, collapse = " | ")
        }
      }
    }

    data.frame(family = fam, species = spp, vernacular = vern,
               file = f, stringsAsFactors = FALSE)
  })
  do.call(rbind, parsed)
}


# ==============================================================================
# UI string translations (search bar, count, footer)
# ==============================================================================
.minisite_ui_strings <- list(
  search_placeholder = c(
    en = "Search species, family or vernacular name…",
    pt = "Pesquisar espécie, família ou nome popular…",
    fr = "Rechercher espèce, famille ou nom vernaculaire…",
    es = "Buscar especie, familia o nombre vernáculo…"
  ),
  species_singular = c(en = "species", pt = "espécie",  fr = "espèce", es = "especie"),
  species_plural = c(en = "species", pt = "espécies", fr = "espèces", es = "especies"),
  family_singular = c(en = "family", pt = "família", fr = "famille", es = "familia"),
  family_plural = c(en = "families", pt = "famílias", fr = "familles", es = "familias"),
  of_count = c(en = "of",  pt = "de",  fr = "sur", es = "de"),
  no_results = c(
    en = "No species match your search.",
    pt = "Nenhuma espécie encontrada.",
    fr = "Aucune espèce ne correspond à votre recherche.",
    es = "No se encontraron especies."
  ),
  generated_with = c(en = "Generated with", pt = "Gerado com",
                     fr = "Généré avec", es = "Generado con"),
  lang_btn_label = c(en = "English", pt = "Português",
                     fr = "Français", es = "Español")
)

# Dashboard labels per language (all dynamically updated by JS via data-i18n)
.dash_labels <- list(
  en = list(
    title = "Collection Overview",
    species = "Species", genera = "Genera", families = "Families",
    origin = "Species by origin",
    phyto = "Species by phytogeographic domain",
    states = "Distribution in Brazil",
    countries = "World distribution",
    top_states = "top states", top_countries = "top countries",
    top_phyto = "top domains",
    spp_abbr = "spp."
  ),
  pt = list(
    title = "Visão Geral da Coleção",
    species = "Espécies", genera = "Gêneros", families = "Famílias",
    origin = "Espécies por origem",
    phyto = "Espécies por domínio fitogeográfico",
    states = "Distribuição no Brasil",
    countries = "Distribuição mundial",
    top_states = "principais estados", top_countries = "principais países",
    top_phyto = "principais domínios",
    spp_abbr = "spp."
  ),
  fr = list(
    title = "Aperçu de la Collection",
    species = "Espèces", genera = "Genres", families = "Familles",
    origin = "Espèces par origine",
    phyto = "Espèces par domaine phytogéographique",
    states = "Distribution au Brésil",
    countries = "Distribution mondiale",
    top_states = "principaux états", top_countries = "principaux pays",
    top_phyto = "principaux domaines",
    spp_abbr = "spp."
  ),
  es = list(
    title = "Resumen de la Colección",
    species = "Especies", genera = "Géneros", families = "Familias",
    origin = "Especies por origen",
    phyto = "Especies por dominio fitogeográfico",
    states = "Distribución en Brasil",
    countries = "Distribución mundial",
    top_states = "principales estados", top_countries = "principales países",
    top_phyto = "principales dominios",
    spp_abbr = "spp."
  )
)


# ==============================================================================
# Minimal HTML escaping
# ==============================================================================
.html_escape <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

# ==============================================================================
# Map establishment-means value to hex colour
# ==============================================================================
.establish_color <- function(val) {
  v <- tolower(trimws(val))
  if (v %in% c("native", "nativa", "indígena")) "#2c5f2d"
  else if (v %in% c("naturalized", "naturalizada")) "#7b5ea7"
  else if (v %in% c("cultivated", "cultivada",
                    "introduced", "introduzida")) "#e07b39"
  else "#95a5a6"
}


# ==============================================================================
# Compute dashboard statistics
# ==============================================================================
.compute_dashboard_stats <- function(species_df, mined_df){
  matched <- mined_df[mined_df$taxonName %in% species_df$species, ]

  n_species  <- nrow(species_df)
  n_genera <- length(unique(
    vapply(strsplit(species_df$species, " "), `[[`, character(1L), 1L)))
  n_families <- length(unique(species_df$family))

  # Helper: split a pipe-separated column, deduplicate per row
  .pipe_counts <- function(col){
    vals <- col[!is.na(col) & nzchar(col)]
    if (length(vals) == 0L) return(integer(0L))
    all_vals <- unlist(lapply(vals, function(x)
      unique(trimws(strsplit(x, "\\s*\\|\\s*")[[1L]]))))
    sort(table(all_vals), decreasing = TRUE)
  }

  # Establishment means
  estab_raw    <- matched$FFB.establishmentMeans
  estab_raw    <- estab_raw[!is.na(estab_raw) & nzchar(estab_raw)]
  counts <- if (length(estab_raw) > 0L) {
    tab <- sort(table(estab_raw), decreasing = TRUE)
    tab[tab > 0L]
  } else integer(0L)

  list(
    n_species = n_species,
    n_genera = n_genera,
    n_families = n_families,
    estab_counts = counts,
    state_counts = .pipe_counts(matched$FFB.stateProvince),
    phyto_counts = .pipe_counts(matched$FFB.phytogeographicDomain),
    country_counts = .pipe_counts(matched$country)
  )
}


# ==============================================================================
# CSS conic-gradient donut chart (HTML string)
# ==============================================================================
.build_donut_html <- function(counts, total, unit_label, color_func = NULL) {
  if (length(counts) == 0L || sum(counts) == 0L) return("")
  total_counts <- sum(counts)

  # Assign colours
  if (is.function(color_func)) {
    cols <- vapply(names(counts), color_func, character(1L))
  } else {
    sober_palette <- c("#5B8C5A", "#7BAC6C","#3B6E5E", "#2C5F6B",
                       "#1F4F5E", "#C4B59F","#8B7D6B","#A69C7A",
                       "#3E5C4A","#9CAF9E")
    n <- length(counts)
    cols <- rep_len(sober_palette, n)
    names(cols) <- names(counts)
  }

  prev_deg <- 0
  stops <- vapply(seq_along(counts), function(i) {
    end_deg <- round(prev_deg + counts[i] / total_counts * 360, 2)
    s <- paste0(cols[i], " ", prev_deg, "deg ", end_deg, "deg")
    prev_deg <<- end_deg
    s
  }, character(1L))

  legend_rows <- paste(vapply(seq_along(counts), function(i) {
    pct <- round(counts[i] / total_counts * 100)
    paste0(
      '<div class="legend-item">',
      '<span class="legend-dot" style="background:', cols[i], '"></span>',
      '<span class="legend-text">', .html_escape(names(counts)[i]), '</span>',
      '<span class="legend-pct">', counts[i], '&nbsp;(', pct, '%)</span>',
      '</div>'
    )
  }, character(1L)), collapse = "\n")

  paste0(
    '<div class="donut-wrap">',
    '<div class="donut" style="background:conic-gradient(',
    paste(stops, collapse = ", "), ')">',
    '<div class="donut-hole">',
    '<span class="donut-n">', total, '</span>',
    '<span class="donut-unit">', .html_escape(unit_label), '</span>',
    '</div></div>',
    '<div class="donut-legend">', legend_rows, '</div>',
    '</div>'
  )
}

# ==============================================================================
# Horizontal bar chart (HTML string)
# ==============================================================================
.build_bar_chart_html <- function(counts, color = "#2c5f2d",
                                  max_show = 27L, wide_label = FALSE){
  if (length(counts) == 0L) return("<em style='color:#bbb'>--</em>")
  counts  <- sort(counts, decreasing = TRUE)
  if (length(counts) > max_show) counts <- counts[seq_len(max_show)]
  max_val <- max(counts)
  lbl_cls <- if (wide_label) "bar-label-wide" else "bar-label"

  rows <- vapply(seq_along(counts), function(i){
    pct <- round(counts[i] / max_val * 100, 1)
    paste0(
      '<div class="bar-row">',
      '<span class="', lbl_cls, '">', .html_escape(names(counts)[i]), '</span>',
      '<div class="bar-track"><div class="bar-fill" style="width:', pct,
      '%;background:', color, '"></div></div>',
      '<span class="bar-count">', counts[i], '</span>',
      '</div>'
    )
  }, character(1L))

  paste0('<div class="bar-chart">', paste(rows, collapse = "\n"), '</div>')
}


# ==============================================================================
# Dashboard section HTML
# -- text elements carry data-i18n attributes so JS can translate them live
# ==============================================================================
.build_dashboard_section_html <- function(dash, lbl, lang_buttons_html){

  # ---- Stat cards ---------------------------------------------------------
  stat_cards <- paste0(
    '<div class="stat-row">',
    '<div class="stat-card" style="border-top-color:#2c5f2d">',
    '<div class="stat-num" style="color:#2c5f2d">', dash$n_species, '</div>',
    '<div class="stat-lbl" data-i18n="species">', .html_escape(lbl$species), '</div>',
    '</div>',
    '<div class="stat-card" style="border-top-color:#1a5276">',
    '<div class="stat-num" style="color:#1a5276">', dash$n_genera, '</div>',
    '<div class="stat-lbl" data-i18n="genera">', .html_escape(lbl$genera), '</div>',
    '</div>',
    '<div class="stat-card" style="border-top-color:#7d6608">',
    '<div class="stat-num" style="color:#7d6608">', dash$n_families, '</div>',
    '<div class="stat-lbl" data-i18n="families">', .html_escape(lbl$families), '</div>',
    '</div>',
    '</div>'
  )

  # ---- Origin donut -------------------------------------------------------
  donut_html <- .build_donut_html(
    counts = dash$estab_counts,
    total = dash$n_species,
    unit_label = lbl$spp_abbr,
    color_func = .establish_color
  )
  donut_panel <- if (nchar(donut_html) > 0L) paste0(
    '<div class="chart-panel">',
    '<h3 class="chart-title" data-i18n="origin">', .html_escape(lbl$origin), '</h3>',
    donut_html, '</div>'
  ) else ""

  # ---- Brazilian states bar chart -----------------------------------------
  n_states <- min(27L, length(dash$state_counts))
  states_panel <- if (length(dash$state_counts) > 0L) {
    sub_lbl <- if (n_states < length(dash$state_counts))
      paste0(" <small>(", lbl$top_states, ")</small>") else ""
    paste0(
      '<div class="chart-panel">',
      '<h3 class="chart-title" data-i18n="states">', .html_escape(lbl$states), '</h3>', sub_lbl,
      .build_bar_chart_html(dash$state_counts, color = "#2c8c9c", max_show = n_states),
      '</div>'
    )
  } else ""

  # ---- Phytogeographic domain donut ---------------------------------------
  phyto_donut_html <- if (length(dash$phyto_counts) > 0L) {
    .build_donut_html(
      counts = dash$phyto_counts,
      total = dash$n_species,
      unit_label = lbl$spp_abbr,
      color_func = NULL
    )
  } else ""
  phyto_donut_panel <- if (nchar(phyto_donut_html) > 0L) {
    paste0(
      '<div class="chart-panel">',
      '<h3 class="chart-title" data-i18n="phyto">', .html_escape(lbl$phyto), '</h3>',
      phyto_donut_html,
      '</div>'
    )
  } else ""

  # ---- World distribution panel -------------------------------------------
  n_ctry <- min(25L, length(dash$country_counts))
  countries_panel <- if (length(dash$country_counts) > 0L) {
    sub_lbl <- if (n_ctry < length(dash$country_counts))
      paste0(" <small>(", lbl$top_countries, ")</small>") else ""
    paste0(
      '<div class="chart-panel chart-wide">',
      '<h3 class="chart-title" data-i18n="countries">', .html_escape(lbl$countries), '</h3>', sub_lbl,
      .build_bar_chart_html(dash$country_counts, color = "#1a5276", max_show = n_ctry, wide_label = TRUE),
      '</div>'
    )
  } else ""

  # ---- Header row ------------------------------------------
  lang_div <- if (nzchar(lang_buttons_html))
    paste0('<div class="dash-lang-group">', lang_buttons_html, '</div>')
  else ""

  # ---- Assemble final dashboard -------------------------------------------
  paste0(
    '<section class="dashboard">\n',
    '  <div class="dashboard-inner">\n',
    '    <div class="dash-header-row">\n',
    '      <h2 class="dash-title" data-i18n="title">', .html_escape(lbl$title), '</h2>\n',
    '      ', lang_div, '\n',
    '    </div>\n',
    '    ', stat_cards, '\n',
    '    <div class="chart-row">\n',
    '      <div style="flex: 1; display: flex; flex-direction: column; gap: 18px;">\n',
    '        ', donut_panel, '\n',
    '        ', phyto_donut_panel, '\n',
    '      </div>\n',
    '      ', states_panel, '\n',
    '    </div>\n',
    '    ', countries_panel, '\n',
    '  </div>\n',
    '</section>\n'
  )
}

# ==============================================================================
# Build the complete minisite HTML string
# ==============================================================================
.build_minisite_html <- function(species_df, mined_df, site_title,
                                 printed_lang, logo_data_uri, logo_url,
                                 group_by_family){

  n_species <- nrow(species_df)
  n_families <- length(unique(species_df$family))

  species_df   <- species_df[order(species_df$family, species_df$species), ]
  esc_title    <- .html_escape(site_title)
  initial_lang <- printed_lang[1L]
  multi_lang   <- length(printed_lang) > 1L
  has_dashboard <- !is.null(mined_df)

  # ---- Language button markup ------------------------------------------------
  lang_buttons_html <- ""
  if (multi_lang) {
    btns <- sapply(printed_lang, function(lang) {
      active <- if (lang == initial_lang) ' class="lang-btn active"'
      else ' class="lang-btn"'
      paste0('<button', active, ' data-lang="', lang, '">',
             unname(.minisite_ui_strings$lang_btn_label[lang]), "</button>")
    })
    lang_buttons_html <- paste(btns, collapse = "\n")
  }

  # ---- Dashboard section ----------------------------------------------------
  dash_section <- ""
  if (has_dashboard) {
    dash <- .compute_dashboard_stats(species_df, mined_df)
    dlbl <- .dash_labels[[initial_lang]]
    if (is.null(dlbl)) dlbl <- .dash_labels[["en"]]
    dash_section <- .build_dashboard_section_html(dash, dlbl, lang_buttons_html)
  }

  # ---- Species JSON ----------------------------------------------------------
  species_json <- jsonlite::toJSON(
    list(family = species_df$family,
         species = species_df$species,
         vernacular = species_df$vernacular,
         file = species_df$file),
    auto_unbox = FALSE
  )

  # ---- UI strings JSON -------------------------------------------------------
  ui_by_lang <- lapply(printed_lang, function(lang) {
    s <- .minisite_ui_strings
    list(
      searchPlaceholder = unname(s$search_placeholder[lang]),
      speciesSingular = unname(s$species_singular[lang]),
      speciesPlural = unname(s$species_plural[lang]),
      familySingular = unname(s$family_singular[lang]),
      familyPlural = unname(s$family_plural[lang]),
      ofCount = unname(s$of_count[lang]),
      noResults = unname(s$no_results[lang]),
      generatedWith = unname(s$generated_with[lang])
    )
  })
  names(ui_by_lang) <- printed_lang
  ui_strings_json <- jsonlite::toJSON(ui_by_lang, auto_unbox = TRUE)

  # Serialize all dashboard label translations for live JS switching
  dash_labels_json <- jsonlite::toJSON(.dash_labels, auto_unbox = TRUE)

  # ---- Logo markup ----------------------------------------------------------
  logo_markup <- ""
  if (!is.null(logo_data_uri)) {
    img <- paste0('<img src="', logo_data_uri,
                  '" alt="Collection logo" style="max-height:100px;width:auto;">')
    logo_markup <- if (!is.null(logo_url) && nzchar(logo_url))
      paste0('<a href="', logo_url,
             '" target="_blank" rel="noopener noreferrer">', img, "</a>")
    else img
  }

  # Language buttons in search bar ONLY when there is no dashboard
  # (if dashboard exists they are in the dash-header-row)
  search_lang_bar <- if (!has_dashboard && nzchar(lang_buttons_html))
    paste0("      ", gsub("\n", "\n      ", lang_buttons_html), "\n")
  else ""

  # ---- CSS ------------------------------------------------------------------
  css <- '
    *, *::before, *::after { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
      margin: 0; padding: 0; background: #f4f6f4; color: #2c3e50; line-height: 1.6;
    }
    /* header */
    header {
      background: linear-gradient(135deg, #2c5f2d 0%, #1e3a1f 100%);
      color: white; padding: 32px 24px 28px;
    }
    .header-inner {
      max-width: 980px; margin: 0 auto;
      display: flex; align-items: center;
      justify-content: space-between; gap: 20px; flex-wrap: wrap;
    }
    .header-text { flex: 1; min-width: 0; }
    h1 { margin: 0 0 4px; font-size: 2rem; font-weight: 700; letter-spacing: -0.5px; }
    .subtitle { font-size: 1rem; opacity: 0.85; margin: 0; }
    .logo-area { flex-shrink: 0; }
    /* dashboard */
    .dashboard { background: #fff; border-bottom: 2px solid #e8f5e9; }
    .dashboard-inner { max-width: 980px; margin: 0 auto; padding: 24px 24px 20px; }
    /* dashboard header row: title left, lang buttons right */
    .dash-header-row {
      display: flex; align-items: center;
      justify-content: space-between; gap: 12px;
      margin-bottom: 20px; flex-wrap: wrap;
    }
    .dash-title {
      font-size: 0.78rem; font-weight: 700; color: #2c5f2d;
      margin: 0; text-transform: uppercase; letter-spacing: 1px;
    }
    .dash-lang-group { display: flex; gap: 6px; flex-wrap: wrap; }
    /* stat cards */
    .stat-row { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 20px; }
    .stat-card {
      flex: 1; min-width: 110px; background: #fafcfa;
      border-radius: 10px; border-top: 4px solid #2c5f2d;
      padding: 16px 14px; box-shadow: 0 1px 5px rgba(0,0,0,0.07);
      text-align: center;
    }
    .stat-num { font-size: 2.4rem; font-weight: 700; line-height: 1; }
    .stat-lbl {
      font-size: 0.75rem; color: #999; margin-top: 5px;
      text-transform: uppercase; letter-spacing: 0.6px;
    }
    /* chart layout */
    .chart-row { display: flex; gap: 18px; flex-wrap: wrap; margin-bottom: 18px; }
    .chart-panel {
      flex: 1; min-width: 260px; background: #fafcfa;
      border-radius: 10px; border: 1px solid #e8ede8;
      padding: 16px 18px 14px;
    }
    .chart-wide { flex: 0 0 100%; min-width: 0; }
    .chart-title {
      margin: 0 0 14px; font-size: 0.78rem; font-weight: 700;
      color: #666; text-transform: uppercase; letter-spacing: 0.5px;
    }
    .chart-title small { font-weight: 400; color: #bbb; text-transform: none; }
    /* donut */
    .donut-wrap { display: flex; align-items: center; gap: 20px; flex-wrap: wrap; }
    .donut {
      position: relative; width: 130px; height: 130px;
      border-radius: 50%; flex-shrink: 0;
      box-shadow: 0 2px 8px rgba(0,0,0,0.12);
    }
    .donut-hole {
      position: absolute; top: 50%; left: 50%;
      transform: translate(-50%,-50%);
      width: 58%; height: 58%; background: #fafcfa; border-radius: 50%;
      display: flex; flex-direction: column;
      align-items: center; justify-content: center; text-align: center;
    }
    .donut-n { font-size: 1.3rem; font-weight: 700; color: #2c3e50; line-height: 1; }
    .donut-unit { font-size: 0.62rem; color: #aaa; }
    .donut-legend { flex: 1; min-width: 0; }
    .legend-item {
      display: flex; align-items: center; gap: 8px;
      margin-bottom: 7px; font-size: 0.82rem;
    }
    .legend-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
    .legend-text { flex: 1; color: #444; }
    .legend-pct { font-weight: 600; color: #2c3e50; white-space: nowrap; }
    /* bar chart */
    .bar-chart { display: flex; flex-direction: column; gap: 5px; }
    .bar-row { display: flex; align-items: center; gap: 7px; }
    .bar-label {
      min-width: 34px; width: 34px; text-align: right;
      font-size: 0.76rem; color: #555; font-weight: 600; flex-shrink: 0;
    }
    .bar-label-wide {
      min-width: 130px; width: 130px; text-align: right;
      font-size: 0.76rem; color: #555; font-weight: 500; flex-shrink: 0;
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }
    .bar-track { flex: 1; height: 13px; background: #eee; border-radius: 7px; overflow: hidden; }
    .bar-fill   { height: 100%; border-radius: 7px; }
    .bar-count  { min-width: 26px; text-align: right; font-size: 0.72rem; color: #aaa; flex-shrink: 0; }
    /* sticky search bar */
    .search-bar {
      background: white; border-bottom: 1px solid #e0e0e0;
      padding: 14px 24px; position: sticky; top: 0; z-index: 100;
      box-shadow: 0 2px 8px rgba(0,0,0,0.07);
    }
    .search-bar-inner {
      max-width: 980px; margin: 0 auto;
      display: flex; gap: 10px; align-items: center; flex-wrap: wrap;
    }
    #searchInput {
      flex: 1; min-width: 200px; padding: 9px 14px;
      border: 2px solid #ddd; border-radius: 8px;
      font-size: 0.95rem; outline: none; transition: border-color 0.2s;
    }
    #searchInput:focus { border-color: #2c5f2d; }
    #searchCount { font-size: 0.85rem; color: #888; white-space: nowrap; }
    /* language buttons */
    .lang-btn {
      padding: 6px 12px; border: 1px solid #d4e4d4; border-radius: 7px;
      background: #f0f7f0; cursor: pointer; font-size: 0.80rem;
      font-weight: 500; color: #2c5f2d; white-space: nowrap;
      transition: background 0.2s, color 0.2s, transform 0.15s;
    }
    .lang-btn:hover { background: #daeeda; transform: translateY(-1px); }
    .lang-btn.active { background: #2c5f2d; color: white; border-color: #2c5f2d; }
    .lang-btn.active:hover { background: #1e3a1f; }
    /* main */
    main { max-width: 980px; margin: 0 auto; padding: 24px; }
    /* family sections */
    .family-section { margin-bottom: 32px; }
    .family-header {
      font-variant: small-caps; font-size: 1.2rem; color: #2c5f2d;
      letter-spacing: 0.5px; margin: 0 0 12px; padding-bottom: 6px;
      border-bottom: 2px solid #e8f5e9;
      display: flex; align-items: baseline; gap: 10px;
    }
    .family-count { font-variant: normal; font-size: 0.78rem; color: #aaa; font-weight: normal; }
    /* species grid */
    .species-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: 10px;
    }
    .species-card {
      background: white; border-left: 4px solid #2c5f2d;
      border-radius: 4px; padding: 13px 15px;
      text-decoration: none; color: inherit; display: block;
      box-shadow: 0 1px 3px rgba(0,0,0,0.07);
      transition: transform 0.15s ease, box-shadow 0.15s ease, border-left-color 0.15s;
    }
    .species-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 14px rgba(44,95,45,0.15);
      border-left-color: #1e3a1f;
    }
    .species-name {
      font-style: italic; font-size: 0.97rem; font-weight: 600;
      color: #2c3e50; display: block; margin-bottom: 3px;
    }
    /* vernacular names -- allow wrapping for long lists */
    .species-sub {
      font-size: 0.74rem; color: #999; display: block; line-height: 1.4;
    }
    /* no-results */
    #noResults {
      text-align: center; padding: 48px 24px;
      color: #aaa; font-size: 1rem; display: none;
    }
    /* footer */
    footer {
      text-align: center; padding: 20px; font-size: 0.78rem;
      color: #bbb; border-top: 1px solid #eee; margin-top: 8px;
    }
    footer a { color: #2c5f2d; text-decoration: none; }
    footer a:hover { text-decoration: underline; }
    /* responsive */
    @media (max-width: 640px) {
      header { padding: 20px 16px; }
      h1 { font-size: 1.4rem; }
      main, .dashboard-inner { padding: 16px; }
      .species-grid { grid-template-columns: 1fr 1fr; }
      .stat-card { min-width: 80px; padding: 12px 10px; }
      .stat-num  { font-size: 1.8rem; }
      .bar-label-wide { min-width: 90px; width: 90px; }
    }
    @media (max-width: 380px) {
      .species-grid { grid-template-columns: 1fr; }
    }
  '

  # ---- JavaScript -----------------------------------------------------------
  js <- paste0(
    "(function () {\n",
    "  var allSpecies    = ", species_json, ";\n",
    "  var uiStrings     = ", ui_strings_json, ";\n",
    "  var dashLabels    = ", dash_labels_json, ";\n",
    "  var groupByFamily = ", if (isTRUE(group_by_family)) "true" else "false", ";\n",
    "  var nTotal    = ", n_species,  ";\n",
    "  var nFamilies = ", n_families, ";\n",
    "  var currentLang = '", initial_lang, "';\n",
    "  var currentFilteredCount = nTotal;\n",
    "\n",
    # applyLanguage -- updates search bar + all data-i18n elements in dashboard
    "  function applyLanguage(lang) {\n",
    "    var ui = uiStrings[lang]; if (!ui) return;\n",
    "    var dl = dashLabels[lang] || dashLabels['en'] || {};\n",
    "    currentLang = lang;\n",
    "    // search bar\n",
    "    document.getElementById('searchInput').placeholder = ui.searchPlaceholder;\n",
    "    var spWord  = nTotal === 1 ? ui.speciesSingular : ui.speciesPlural;\n",
    "    var famWord = nFamilies === 1 ? ui.familySingular : ui.familyPlural;\n",
    "    document.getElementById('subtitleEl').textContent =\n",
    "      nTotal + ' ' + spWord + ' · ' + nFamilies + ' ' + famWord;\n",
    "    document.getElementById('noResults').textContent = ui.noResults;\n",
    "    document.getElementById('generatedWith').textContent = ui.generatedWith;\n",
    "    updateCount(currentFilteredCount);\n",
    "    // lang buttons (all sets on page)\n",
    "    document.querySelectorAll('.lang-btn').forEach(function (btn) {\n",
    "      btn.classList.toggle('active', btn.dataset.lang === lang);\n",
    "    });\n",
    "    // dashboard: translate every [data-i18n] element\n",
    "    document.querySelectorAll('[data-i18n]').forEach(function (el) {\n",
    "      var key = el.getAttribute('data-i18n');\n",
    "      var val = dl[key];\n",
    "      if (val) el.textContent = val;\n",
    "    });\n",
    "  }\n",
    "\n",
    # updateCount
    "  function updateCount(n) {\n",
    "    currentFilteredCount = n;\n",
    "    var ui = uiStrings[currentLang];\n",
    "    var el = document.getElementById('searchCount');\n",
    "    var spWord = n === 1 ? ui.speciesSingular : ui.speciesPlural;\n",
    "    el.textContent = (n === nTotal)\n",
    "      ? (nTotal + ' ' + spWord)\n",
    "      : (n + ' ' + ui.ofCount + ' ' + nTotal + ' ' + spWord);\n",
    "  }\n",
    "\n",
    # makeCard -- show all vernacular names if present, nothing if absent
    "  function makeCard(species, vernacular, fam, href) {\n",
    "    var a = document.createElement('a');\n",
    "    a.href = href; a.className = 'species-card';\n",
    "    var sub = (vernacular && vernacular.length > 0)\n",
    "      ? '<span class=\"species-sub\">' + vernacular + '</span>'\n",
    "      : '';\n",
    "    a.innerHTML =\n",
    "      '<span class=\"species-name\"><em>' + species + '</em></span>' + sub;\n",
    "    return a;\n",
    "  }\n",
    "\n",
    # buildList
    "  function buildList(d) {\n",
    "    var mainEl = document.getElementById('speciesMain');\n",
    "    var noRes  = document.getElementById('noResults');\n",
    "    mainEl.innerHTML = '';\n",
    "    if (d.family.length === 0) {\n",
    "      noRes.style.display = 'block'; updateCount(0); return;\n",
    "    }\n",
    "    noRes.style.display = 'none';\n",
    "    updateCount(d.family.length);\n",
    "    if (groupByFamily) {\n",
    "      var families = {};\n",
    "      for (var i = 0; i < d.family.length; i++) {\n",
    "        var fam = d.family[i];\n",
    "        if (!families[fam]) families[fam] = [];\n",
    "        families[fam].push({ species: d.species[i],\n",
    "          vernacular: d.vernacular[i], file: d.file[i] });\n",
    "      }\n",
    "      Object.keys(families).sort().forEach(function (fam) {\n",
    "        var sec = document.createElement('div');\n",
    "        sec.className = 'family-section';\n",
    "        var hdr = document.createElement('h2');\n",
    "        hdr.className = 'family-header';\n",
    "        var ui = uiStrings[currentLang];\n",
    "        hdr.innerHTML = fam +\n",
    "          '<span class=\"family-count\">' + families[fam].length + ' ' +\n",
    "          (families[fam].length === 1\n",
    "            ? ui.speciesSingular : ui.speciesPlural) + '</span>';\n",
    "        sec.appendChild(hdr);\n",
    "        var grid = document.createElement('div');\n",
    "        grid.className = 'species-grid';\n",
    "        families[fam].forEach(function (sp) {\n",
    "          grid.appendChild(makeCard(sp.species, sp.vernacular, fam, sp.file));\n",
    "        });\n",
    "        sec.appendChild(grid); mainEl.appendChild(sec);\n",
    "      });\n",
    "    } else {\n",
    "      var grid = document.createElement('div');\n",
    "      grid.className = 'species-grid';\n",
    "      for (var j = 0; j < d.family.length; j++) {\n",
    "        grid.appendChild(makeCard(\n",
    "          d.species[j], d.vernacular[j], d.family[j], d.file[j]));\n",
    "      }\n",
    "      mainEl.appendChild(grid);\n",
    "    }\n",
    "  }\n",
    "\n",
    # filterSpecies -- species + family + all vernacular names
    "  function filterSpecies(query) {\n",
    "    var q = query.toLowerCase().trim();\n",
    "    if (!q) { buildList(allSpecies); return; }\n",
    "    var f = { family: [], species: [], vernacular: [], file: [] };\n",
    "    for (var i = 0; i < allSpecies.family.length; i++) {\n",
    "      var s = (allSpecies.species[i]     + ' ' +\n",
    "               allSpecies.family[i]      + ' ' +\n",
    "               (allSpecies.vernacular[i] || '')).toLowerCase();\n",
    "      if (s.indexOf(q) !== -1) {\n",
    "        f.family.push(allSpecies.family[i]);\n",
    "        f.species.push(allSpecies.species[i]);\n",
    "        f.vernacular.push(allSpecies.vernacular[i]);\n",
    "        f.file.push(allSpecies.file[i]);\n",
    "      }\n",
    "    }\n",
    "    buildList(f);\n",
    "  }\n",
    "\n",
    # Event listeners + init
    "  document.getElementById('searchInput').addEventListener('input', function () {\n",
    "    filterSpecies(this.value);\n",
    "  });\n",
    "  document.querySelectorAll('.lang-btn').forEach(function (btn) {\n",
    "    btn.addEventListener('click', function () {\n",
    "      applyLanguage(this.dataset.lang);\n",
    "      filterSpecies(document.getElementById('searchInput').value);\n",
    "    });\n",
    "  });\n",
    "  applyLanguage(currentLang);\n",
    "  buildList(allSpecies);\n",
    "})();\n"
  )

  # ---- Assemble final HTML --------------------------------------------------
  logo_div <- if (nzchar(logo_markup))
    paste0('      <div class="logo-area">', logo_markup, "</div>\n")
  else ""

  paste0(
    "<!DOCTYPE html>\n",
    '<html lang="', initial_lang, '">\n',
    "<head>\n",
    '  <meta charset="UTF-8">\n',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n',
    "  <title>", esc_title, "</title>\n",
    "  <style>\n", css, "\n  </style>\n",
    "</head>\n",
    "<body>\n",
    "  <header>\n",
    '    <div class="header-inner">\n',
    '      <div class="header-text">\n',
    "        <h1>", esc_title, "</h1>\n",
    '        <p class="subtitle" id="subtitleEl"></p>\n',
    "      </div>\n",
    logo_div,
    "    </div>\n",
    "  </header>\n",
    dash_section,
    '  <div class="search-bar">\n',
    '    <div class="search-bar-inner">\n',
    '      <input type="text" id="searchInput" autocomplete="off">\n',
    '      <span id="searchCount"></span>\n',
    search_lang_bar,
    "    </div>\n",
    "  </div>\n",
    '  <main id="speciesMain"></main>\n',
    '  <p id="noResults"></p>\n',
    "  <footer>\n",
    '    <span id="generatedWith"></span>',
    ' <a href="https://dboslab.github.io/aRboretum/"',
    ' target="_blank" rel="noopener noreferrer">aRboretum</a>\n',
    "  </footer>\n",
    "  <script>\n", js, "  </script>\n",
    "</body>\n",
    "</html>\n"
  )
}
