#' Create folder structure and phrase files for personal audio recordings
#'
#' @author
#' Martin Boucknooghe & Domingos Cardoso
#'
#' @description
#' This function creates an organized folder structure for storing personal audio
#' recordings of species descriptions and generates an HTML guide with the phrases
#' to be recorded. It is designed to be used **after** running `arboretum_data()`
#' and **before** running `arboretum_labels()` when users want to provide their
#' own audio files instead of relying only on browser text-to-speech.
#'
#' In addition to the built-in translated languages (`"pt"`, `"en"`, `"fr"`,
#' and `"es"`), the function can optionally prepare folders for one additional
#' language through `add_lang`. This is useful when a project needs to include
#' community-based or locally relevant audio, such as recordings in an Indigenous
#' language, even if that language is not yet fully incorporated into the package
#' interface or translation system.
#'
#' The `add_lang` argument is intended as a flexible, intermediate solution:
#' it allows users to organize and add personal audio for an extra language while
#' the rest of the website remains in the package-supported interface languages.
#'
#' @param data_path Character string. Path to the input data file (CSV or Excel format)
#'   generated by `arboretum_data()`.
#' @param printed_lang Character vector. Built-in language(s) to generate folders and
#'   phrases for. Accepted values are `"pt"`, `"en"`, `"fr"`, and `"es"`.
#' @param add_lang Character string or `NULL`. Optional code for one additional
#'   language to include in the folder structure for personal recordings, for
#'   example `"PANARA"` or `"TUKANO"`. This argument is intended for cases where
#'   users want to add custom community or local-language audio without translating
#'   the full package interface. When supplied, one extra recording folder per
#'   species is created using that language code.
#' @param verbose Logical. If `TRUE`, prints progress messages to the console.
#'
#' @return Invisibly returns `NULL`.
#'
#' @details
#' The function creates an `arboretum_audios/` directory containing one folder per
#' species-language combination. Folder names follow the pattern:
#'
#' \preformatted{
#' FAMILY_Genus_species_LANG
#' }
#'
#' where `LANG` is one of `PT`, `EN`, `FR`, `ES`, or the custom value supplied in
#' `add_lang`.
#'
#' It also creates an HTML file named:
#'
#' \preformatted{
#' arboretum_audios/__personal_audio_recording_guide.html
#' }
#'
#' This guide helps users navigate across species and languages when preparing
#' personal recordings.
#'
#' @note
#' `add_lang` does not create a full translation workflow for the package interface.
#' It only prepares an additional language slot for custom audio recording, and is
#' especially useful in collaborative projects where accessibility in a community
#' language is needed before a complete website translation is available.
#'
#' @importFrom utils read.csv
#' @importFrom openxlsx read.xlsx
#' @importFrom tools file_ext
#' @importFrom jsonlite toJSON
#' @export

arboretum_audios <- function(data_path = NULL,
                             printed_lang = c("pt", "en", "fr", "es"),
                             add_lang = NULL,
                             verbose = TRUE) {

  printed_lang <- .arg_check_printed_lang(printed_lang)

  df <- .read_species_data(data_path, verbose)

  audio_dir <- "arboretum_audios"
  lang_codes <- c("EN", "ES", "FR", "PT")

  if (!is.null(add_lang) && nzchar(add_lang)) {
    lang_codes <- unique(c(lang_codes, toupper(add_lang)))
  }

  spp <- gsub("\\s", "_", df$taxonName)
  fam <- toupper(df$family)

  if (!dir.exists(audio_dir)) {
    if (verbose) {
      message("Empty folders for adding personal audios successfully created!\n")
    }
    dir.create(audio_dir, recursive = TRUE)
    for (i in seq_along(spp)) {
      for (lang in lang_codes) {
        folder_path <- file.path(audio_dir, paste(fam[i], spp[i], lang, sep = "_"))
        dir.create(folder_path, recursive = TRUE)
      }
    }
  }


  ui_strings <- .ui_strings()

  lang_button_label <- c(
    en = "English",
    pt = "Português",
    fr = "Français",
    es = "Español"
  )

  missing_langs <- setdiff(printed_lang, names(lang_button_label))
  if (length(missing_langs) > 0) {
    lang_button_label[missing_langs] <- toupper(missing_langs)
  }

  # Generate phrases for each requested language
  phrases_out <- .build_arboretum_phrases(
    data_path = NULL,
    df = df,
    printed_lang = printed_lang,
    add_lang = add_lang,
    verbose = verbose
  )

  printed_lang <- phrases_out$printed_lang
  html_phrases <- phrases_out$html_phrases

  output_path <- file.path(audio_dir, "__personal_audio_recording_guide.html")
  .save_phrase_html(
    df = df,
    function_use = "_audios",
    ui_strings = ui_strings,
    lang_button_label = lang_button_label,
    printed_lang = printed_lang,
    html_phrases = html_phrases,
    output_path = output_path,
    verbose = verbose
  )

  invisible(NULL)
}

